from __future__ import annotations

import json
from pathlib import Path
import unittest

from tests.test_n6_strategy_worker_canonical_acl_079 import (
    _temporary_postgres,
)


ROOT = Path(__file__).resolve().parents[1]
FORWARD = ROOT / "sql/087_n6_strategy_center_30d_archive.sql"
ROLLBACK = ROOT / "sql/087_n6_strategy_center_30d_archive_rollback.sql"
CONTRACT = (
    ROOT
    / "config/n6_strategy_center/"
    "N6_STRATEGY_CENTER_30D_ARCHIVE_RETENTION_CONTRACT_V1.json"
)
EXPECTED_COUNTS = {
    "n6_strategy_package_catalog": 4,
    "n6_user_strategy_selection_revision": 23,
    "n6_user_strategy_selection_item": 32,
    "n6_strategy_match_projection": 863,
    "n6_strategy_observation_projection": 4,
    "n6_strategy_match_change": 186,
}
CORE_FUNCTION_SIGNATURES = (
    "public.n6_strategy_center_trade_date_authority_v1()",
    "public.n6_strategy_default_selection_on_principal_insert()",
    "public.n6_btrack_strategy_center_state(text)",
    "public.n6_btrack_strategy_center_changes(text,bigint,integer)",
    "public.n6_btrack_strategy_selection_put(text,text[],bigint,text)",
    "public.n6_strategy_center_compensate_revision_v1(bigint,text,bigint,bigint,bigint,text,bigint,date,text)",
    "public.n6_strategy_center_abandon_pending_v2(bigint,text,bigint,bigint,bigint,date,text)",
)
OPTIONAL_FUNCTION_SIGNATURES = (
    "public.n6_strategy_center_migrate_v2_selection_v1(bigint,bigint,bigint,bigint,text)",
    "public.n6_strategy_center_owner_create_pending_v2(bigint,bigint,bigint,bigint,text,text,text)",
)
PROTECTED_TABLES = (
    "n6_strategy",
    "n6_ai_strategy_evaluation",
    "n6_ai_strategy_action",
    "n6_ai_position_strategy_episode",
    "n6_virtual_trade_proposal",
    "n6_virtual_order",
    "n6_virtual_trade",
    "n6_virtual_position",
    "n6_virtual_cash",
    "common_trigger_state",
    "common_action_confirmation",
)


def fixture_sql(*, optional_functions: bool) -> str:
    optional = (
        """
        CREATE FUNCTION public.n6_strategy_center_migrate_v2_selection_v1(
          bigint, bigint, bigint, bigint, text
        ) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
        SET search_path = pg_catalog
        AS $$ SELECT pg_catalog.jsonb_build_object('optional', '085') $$;
        ALTER FUNCTION public.n6_strategy_center_migrate_v2_selection_v1(
          bigint, bigint, bigint, bigint, text
        ) OWNER TO ashare_v3_user;
        REVOKE ALL ON FUNCTION
          public.n6_strategy_center_migrate_v2_selection_v1(
            bigint, bigint, bigint, bigint, text
          )
        FROM PUBLIC;

        CREATE FUNCTION public.n6_strategy_center_owner_create_pending_v2(
          bigint, bigint, bigint, bigint, text, text, text
        ) RETURNS jsonb LANGUAGE sql SECURITY DEFINER
        SET search_path = pg_catalog
        AS $$ SELECT pg_catalog.jsonb_build_object('optional', '086') $$;
        ALTER FUNCTION public.n6_strategy_center_owner_create_pending_v2(
          bigint, bigint, bigint, bigint, text, text, text
        ) OWNER TO ashare_v3_user;
        REVOKE ALL ON FUNCTION
          public.n6_strategy_center_owner_create_pending_v2(
            bigint, bigint, bigint, bigint, text, text, text
          )
        FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION
          public.n6_strategy_center_owner_create_pending_v2(
            bigint, bigint, bigint, bigint, text, text, text
          )
        TO n6_strategy_worker;
        """
        if optional_functions
        else ""
    )
    protected = "\n".join(
        f"""
        CREATE TABLE public.{name} (
          id bigint PRIMARY KEY,
          marker text NOT NULL
        );
        INSERT INTO public.{name} VALUES (1, '{name}-protected');
        """
        for name in PROTECTED_TABLES
    )
    return f"""
    CREATE ROLE n6_btrack_web LOGIN NOINHERIT;
    CREATE ROLE n6_virtual_executor LOGIN NOINHERIT;

    GRANT SELECT ON public.v_n6_stock_condition_display_basis
      TO n6_strategy_worker;
    GRANT SELECT ON public.v_n6_index_condition_display_basis
      TO n6_strategy_worker;
    GRANT SELECT ON public.v_n6_board_condition_display_basis
      TO n6_strategy_worker;

    CREATE TABLE public.user_account (
      user_id bigint PRIMARY KEY,
      status text NOT NULL
    );
    CREATE TABLE public.n6_principal (
      principal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      principal_type text NOT NULL,
      owner_user_id bigint NOT NULL REFERENCES public.user_account(user_id),
      principal_status text NOT NULL
    );
    INSERT INTO public.user_account VALUES (1, 'active');
    INSERT INTO public.n6_principal(
      principal_id, principal_type, owner_user_id, principal_status
    ) VALUES (1, 'human_user', 1, 'active');

    CREATE TABLE public.n6_strategy_package_catalog (
      package_catalog_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      package_key text NOT NULL,
      package_version text NOT NULL,
      package_status text NOT NULL,
      UNIQUE(package_key, package_version)
    );
    CREATE TABLE public.n6_user_strategy_selection_revision (
      selection_revision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      principal_id bigint NOT NULL REFERENCES public.n6_principal(principal_id),
      principal_type text NOT NULL,
      user_id bigint NOT NULL REFERENCES public.user_account(user_id),
      revision_no bigint NOT NULL,
      selection_status text NOT NULL,
      previous_revision_id bigint
        REFERENCES public.n6_user_strategy_selection_revision(
          selection_revision_id
        )
    );
    CREATE INDEX idx_087_fixture_revision_scope
      ON public.n6_user_strategy_selection_revision(
        principal_id, user_id, revision_no
      );
    CREATE TABLE public.n6_user_strategy_selection_item (
      selection_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      selection_revision_id bigint NOT NULL
        REFERENCES public.n6_user_strategy_selection_revision(
          selection_revision_id
        ),
      package_catalog_id bigint NOT NULL
        REFERENCES public.n6_strategy_package_catalog(package_catalog_id),
      package_key text NOT NULL,
      package_version text NOT NULL
    );
    CREATE INDEX idx_087_fixture_item_revision
      ON public.n6_user_strategy_selection_item(selection_revision_id);
    CREATE TABLE public.n6_strategy_match_projection (
      strategy_match_projection_id bigint
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      selection_revision_id bigint NOT NULL
        REFERENCES public.n6_user_strategy_selection_revision(
          selection_revision_id
        ),
      identity_key text NOT NULL,
      payload jsonb NOT NULL
    );
    CREATE INDEX idx_087_fixture_match_revision
      ON public.n6_strategy_match_projection(selection_revision_id);
    CREATE TABLE public.n6_strategy_observation_projection (
      strategy_observation_projection_id bigint
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      selection_revision_id bigint NOT NULL
        REFERENCES public.n6_user_strategy_selection_revision(
          selection_revision_id
        ),
      identity_key text NOT NULL,
      payload jsonb NOT NULL
    );
    CREATE INDEX idx_087_fixture_observation_revision
      ON public.n6_strategy_observation_projection(selection_revision_id);
    CREATE TABLE public.n6_strategy_match_change (
      strategy_match_change_id bigint
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      strategy_match_projection_id bigint
        REFERENCES public.n6_strategy_match_projection(
          strategy_match_projection_id
        ),
      event_kind text NOT NULL,
      payload jsonb NOT NULL
    );
    CREATE INDEX idx_087_fixture_change_projection
      ON public.n6_strategy_match_change(strategy_match_projection_id);

    INSERT INTO public.n6_strategy_package_catalog(
      package_key, package_version, package_status
    )
    SELECT 'package_' || ((value - 1) % 2 + 1),
           'v' || ((value - 1) / 2 + 1),
           CASE WHEN value <= 2 THEN 'grandfathered' ELSE 'active' END
    FROM pg_catalog.generate_series(1, 4) value;
    INSERT INTO public.n6_user_strategy_selection_revision(
      principal_id, principal_type, user_id, revision_no, selection_status
    )
    SELECT 1, 'human_user', 1, value,
           CASE WHEN value = 23 THEN 'active' ELSE 'archived' END
    FROM pg_catalog.generate_series(1, 23) value;
    INSERT INTO public.n6_user_strategy_selection_item(
      selection_revision_id, package_catalog_id, package_key, package_version
    )
    SELECT ((value - 1) % 23) + 1,
           ((value - 1) % 4) + 1,
           'package_' || ((value - 1) % 2 + 1),
           'v' || (((value - 1) % 4) / 2 + 1)
    FROM pg_catalog.generate_series(1, 32) value;
    INSERT INTO public.n6_strategy_match_projection(
      selection_revision_id, identity_key, payload
    )
    SELECT ((value - 1) % 23) + 1,
           'stock:SH:' || pg_catalog.lpad(value::text, 6, '0'),
           pg_catalog.jsonb_build_object('value', value)
    FROM pg_catalog.generate_series(1, 863) value;
    INSERT INTO public.n6_strategy_observation_projection(
      selection_revision_id, identity_key, payload
    )
    SELECT value,
           'stock:SZ:' || pg_catalog.lpad(value::text, 6, '0'),
           pg_catalog.jsonb_build_object('value', value)
    FROM pg_catalog.generate_series(1, 4) value;
    INSERT INTO public.n6_strategy_match_change(
      strategy_match_projection_id, event_kind, payload
    )
    SELECT value, 'upsert', pg_catalog.jsonb_build_object('value', value)
    FROM pg_catalog.generate_series(1, 186) value;

    CREATE FUNCTION public.n6_strategy_center_trade_date_authority_v1()
    RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path = pg_catalog
    AS $$ SELECT pg_catalog.jsonb_build_object(
      'for_trade_date', '20260727'
    ) $$;
    CREATE FUNCTION public.n6_strategy_default_selection_on_principal_insert()
    RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
    SET search_path = pg_catalog
    AS $$ BEGIN RETURN NEW; END $$;
    CREATE TRIGGER trg_073_n6_strategy_default_selection
    AFTER INSERT ON public.n6_principal
    FOR EACH ROW EXECUTE FUNCTION
      public.n6_strategy_default_selection_on_principal_insert();
    CREATE FUNCTION public.n6_btrack_strategy_center_state(text)
    RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path = pg_catalog
    AS $$ SELECT pg_catalog.jsonb_build_object('state', 'ready') $$;
    CREATE FUNCTION public.n6_btrack_strategy_center_changes(
      text, bigint, integer
    ) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path = pg_catalog
    AS $$ SELECT pg_catalog.jsonb_build_object('changes', 0) $$;
    CREATE FUNCTION public.n6_btrack_strategy_selection_put(
      text, text[], bigint, text
    ) RETURNS jsonb LANGUAGE sql VOLATILE SECURITY DEFINER
    SET search_path = pg_catalog
    AS $$ SELECT pg_catalog.jsonb_build_object('selection', 'pending') $$;
    CREATE FUNCTION public.n6_strategy_center_compensate_revision_v1(
      bigint, text, bigint, bigint, bigint, text, bigint, date, text
    ) RETURNS jsonb LANGUAGE sql VOLATILE SECURITY DEFINER
    SET search_path = pg_catalog
    AS $$ SELECT pg_catalog.jsonb_build_object('compensation', true) $$;
    CREATE FUNCTION public.n6_strategy_center_abandon_pending_v2(
      bigint, text, bigint, bigint, bigint, date, text
    ) RETURNS jsonb LANGUAGE sql VOLATILE SECURITY DEFINER
    SET search_path = pg_catalog
    AS $$ SELECT pg_catalog.jsonb_build_object('abandoned', true) $$;

    REVOKE ALL ON FUNCTION
      public.n6_strategy_center_trade_date_authority_v1(),
      public.n6_strategy_default_selection_on_principal_insert(),
      public.n6_btrack_strategy_center_state(text),
      public.n6_btrack_strategy_center_changes(text,bigint,integer),
      public.n6_btrack_strategy_selection_put(text,text[],bigint,text),
      public.n6_strategy_center_compensate_revision_v1(
        bigint,text,bigint,bigint,bigint,text,bigint,date,text
      ),
      public.n6_strategy_center_abandon_pending_v2(
        bigint,text,bigint,bigint,bigint,date,text
      )
    FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION
      public.n6_btrack_strategy_center_state(text),
      public.n6_btrack_strategy_center_changes(text,bigint,integer),
      public.n6_btrack_strategy_selection_put(text,text[],bigint,text)
    TO n6_btrack_web;
    GRANT SELECT ON TABLE
      public.n6_strategy_package_catalog,
      public.n6_user_strategy_selection_revision,
      public.n6_user_strategy_selection_item,
      public.n6_strategy_match_projection,
      public.n6_strategy_observation_projection,
      public.n6_strategy_match_change
    TO n6_strategy_worker;
    GRANT INSERT, UPDATE, DELETE ON TABLE
      public.n6_strategy_match_projection,
      public.n6_strategy_observation_projection,
      public.n6_strategy_match_change
    TO n6_strategy_worker;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
    TO n6_strategy_worker;

    {optional}
    {protected}
    """


def protected_fingerprint_sql() -> str:
    tables = ",".join(f"'{name}'" for name in PROTECTED_TABLES)
    return f"""
    SELECT pg_catalog.md5(
      pg_catalog.jsonb_build_object(
        'roles', (
          SELECT pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
              'name', role_row.rolname,
              'super', role_row.rolsuper,
              'inherit', role_row.rolinherit,
              'createdb', role_row.rolcreatedb,
              'createrole', role_row.rolcreaterole,
              'replication', role_row.rolreplication,
              'bypassrls', role_row.rolbypassrls
            ) ORDER BY role_row.rolname
          )
          FROM pg_catalog.pg_roles role_row
          WHERE role_row.rolname IN (
            'n6_strategy_worker', 'n6_virtual_executor'
          )
        ),
        'relations', (
          SELECT pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
              'name', relation.relname,
              'owner', pg_catalog.pg_get_userbyid(relation.relowner),
              'acl', relation.relacl
            ) ORDER BY relation.relname
          )
          FROM pg_catalog.pg_class relation
          JOIN pg_catalog.pg_namespace namespace
            ON namespace.oid = relation.relnamespace
          WHERE namespace.nspname = 'public'
            AND (
              relation.relname IN ({tables})
              OR relation.relname IN (
                'v_n6_stock_condition_display_basis',
                'v_n6_index_condition_display_basis',
                'v_n6_board_condition_display_basis'
              )
            )
        ),
        'rows', (
          SELECT pg_catalog.jsonb_agg(row_value ORDER BY row_value->>'name')
          FROM (
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_strategy', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_strategy value)
            ) row_value
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_ai_strategy_evaluation', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_ai_strategy_evaluation value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_ai_strategy_action', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_ai_strategy_action value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_ai_position_strategy_episode', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_ai_position_strategy_episode value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_virtual_trade_proposal', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_virtual_trade_proposal value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_virtual_order', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_virtual_order value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_virtual_trade', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_virtual_trade value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_virtual_position', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_virtual_position value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'n6_virtual_cash', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.n6_virtual_cash value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'common_trigger_state', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.common_trigger_state value)
            )
            UNION ALL
            SELECT pg_catalog.jsonb_build_object(
              'name', 'common_action_confirmation', 'rows',
              (SELECT pg_catalog.jsonb_agg(
                 pg_catalog.to_jsonb(value) ORDER BY value.id
               ) FROM public.common_action_confirmation value)
            )
          ) protected_rows
        )
      )::text
    )
    """


def strategy_fingerprint_sql() -> str:
    signatures = ",".join(
        f"'{signature}'"
        for signature in CORE_FUNCTION_SIGNATURES + OPTIONAL_FUNCTION_SIGNATURES
    )
    return f"""
    SELECT pg_catalog.md5(
      pg_catalog.jsonb_build_object(
        'relations', (
          SELECT pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
              'name', relation.relname,
              'kind', relation.relkind,
              'owner', pg_catalog.pg_get_userbyid(relation.relowner),
              'acl', relation.relacl,
              'definition', CASE
                WHEN relation.relkind = 'i'
                  THEN pg_catalog.pg_get_indexdef(relation.oid)
                ELSE NULL
              END
            ) ORDER BY relation.relkind, relation.relname
          )
          FROM pg_catalog.pg_class relation
          JOIN pg_catalog.pg_namespace namespace
            ON namespace.oid = relation.relnamespace
          WHERE namespace.nspname = 'public'
            AND (
              relation.relname = ANY(ARRAY[
                'n6_strategy_package_catalog',
                'n6_user_strategy_selection_revision',
                'n6_user_strategy_selection_item',
                'n6_strategy_match_projection',
                'n6_strategy_observation_projection',
                'n6_strategy_match_change'
              ])
              OR relation.oid IN (
                SELECT index_row.indexrelid
                FROM pg_catalog.pg_index index_row
                JOIN pg_catalog.pg_class target
                  ON target.oid = index_row.indrelid
                JOIN pg_catalog.pg_namespace target_namespace
                  ON target_namespace.oid = target.relnamespace
                WHERE target_namespace.nspname = 'public'
                  AND target.relname = ANY(ARRAY[
                    'n6_strategy_package_catalog',
                    'n6_user_strategy_selection_revision',
                    'n6_user_strategy_selection_item',
                    'n6_strategy_match_projection',
                    'n6_strategy_observation_projection',
                    'n6_strategy_match_change'
                  ])
              )
              OR (
                relation.relkind = 'S'
                AND relation.relname LIKE 'n6_%_seq'
              )
            )
        ),
        'constraints', (
          SELECT pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
              'table', target.relname,
              'name', constraint_row.conname,
              'definition', pg_catalog.pg_get_constraintdef(
                constraint_row.oid, true
              )
            ) ORDER BY target.relname, constraint_row.conname
          )
          FROM pg_catalog.pg_constraint constraint_row
          JOIN pg_catalog.pg_class target
            ON target.oid = constraint_row.conrelid
          JOIN pg_catalog.pg_namespace namespace
            ON namespace.oid = target.relnamespace
          WHERE namespace.nspname = 'public'
            AND target.relname = ANY(ARRAY[
              'n6_strategy_package_catalog',
              'n6_user_strategy_selection_revision',
              'n6_user_strategy_selection_item',
              'n6_strategy_match_projection',
              'n6_strategy_observation_projection',
              'n6_strategy_match_change'
            ])
        ),
        'functions', (
          SELECT pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
              'signature', procedure.oid::pg_catalog.regprocedure::text,
              'owner', pg_catalog.pg_get_userbyid(procedure.proowner),
              'acl', procedure.proacl,
              'definition', pg_catalog.pg_get_functiondef(procedure.oid)
            ) ORDER BY procedure.oid::pg_catalog.regprocedure::text
          )
          FROM pg_catalog.pg_proc procedure
          WHERE procedure.oid IN (
            SELECT pg_catalog.to_regprocedure(
              signature_row.function_signature
            )
            FROM pg_catalog.unnest(
              ARRAY[{signatures}]
            ) AS signature_row(function_signature)
            WHERE pg_catalog.to_regprocedure(
              signature_row.function_signature
            ) IS NOT NULL
          )
        ),
        'trigger', (
          SELECT pg_catalog.pg_get_triggerdef(trigger_row.oid, true)
          FROM pg_catalog.pg_trigger trigger_row
          WHERE trigger_row.tgrelid =
            'public.n6_principal'::pg_catalog.regclass
            AND trigger_row.tgname =
              'trg_073_n6_strategy_default_selection'
            AND NOT trigger_row.tgisinternal
        ),
        'rows', (
          SELECT pg_catalog.jsonb_object_agg(
            snapshot.table_name,
            pg_catalog.jsonb_build_object(
              'count', snapshot.row_count,
              'hash', snapshot.row_hash
            )
          )
          FROM (
            SELECT 'n6_strategy_package_catalog'::text table_name,
                   pg_catalog.count(*) row_count,
                   pg_catalog.md5(coalesce(
                     pg_catalog.string_agg(
                       pg_catalog.to_jsonb(value)::text, '|'
                       ORDER BY pg_catalog.to_jsonb(value)::text
                     ), ''
                   )) row_hash
            FROM public.n6_strategy_package_catalog value
            UNION ALL
            SELECT 'n6_user_strategy_selection_revision',
                   pg_catalog.count(*),
                   pg_catalog.md5(coalesce(
                     pg_catalog.string_agg(
                       pg_catalog.to_jsonb(value)::text, '|'
                       ORDER BY pg_catalog.to_jsonb(value)::text
                     ), ''
                   ))
            FROM public.n6_user_strategy_selection_revision value
            UNION ALL
            SELECT 'n6_user_strategy_selection_item',
                   pg_catalog.count(*),
                   pg_catalog.md5(coalesce(
                     pg_catalog.string_agg(
                       pg_catalog.to_jsonb(value)::text, '|'
                       ORDER BY pg_catalog.to_jsonb(value)::text
                     ), ''
                   ))
            FROM public.n6_user_strategy_selection_item value
            UNION ALL
            SELECT 'n6_strategy_match_projection',
                   pg_catalog.count(*),
                   pg_catalog.md5(coalesce(
                     pg_catalog.string_agg(
                       pg_catalog.to_jsonb(value)::text, '|'
                       ORDER BY pg_catalog.to_jsonb(value)::text
                     ), ''
                   ))
            FROM public.n6_strategy_match_projection value
            UNION ALL
            SELECT 'n6_strategy_observation_projection',
                   pg_catalog.count(*),
                   pg_catalog.md5(coalesce(
                     pg_catalog.string_agg(
                       pg_catalog.to_jsonb(value)::text, '|'
                       ORDER BY pg_catalog.to_jsonb(value)::text
                     ), ''
                   ))
            FROM public.n6_strategy_observation_projection value
            UNION ALL
            SELECT 'n6_strategy_match_change',
                   pg_catalog.count(*),
                   pg_catalog.md5(coalesce(
                     pg_catalog.string_agg(
                       pg_catalog.to_jsonb(value)::text, '|'
                       ORDER BY pg_catalog.to_jsonb(value)::text
                     ), ''
                   ))
            FROM public.n6_strategy_match_change value
          ) snapshot
        )
      )::text
    )
    """


class StrategyCenterArchive087Tests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.forward = FORWARD.read_text()
        cls.rollback = ROLLBACK.read_text()
        cls.contract = json.loads(CONTRACT.read_text())

    def test_contract_is_conservative_and_never_auto_drops(self) -> None:
        retention = self.contract["retention"]
        self.assertEqual(retention["duration_days"], 30)
        self.assertTrue(retention["database_anchor_is_conservative"])
        self.assertEqual(
            retention["physical_drop_not_before"],
            "max(database_conservative_deadline_at, artifact_commit_deadline_at)",
        )
        self.assertFalse(retention["automatic_drop"])
        self.assertTrue(retention["drop_requires_independent_authorization"])
        artifact = self.contract["production_execution_artifact"]
        self.assertTrue(artifact["required_after_successful_forward_commit"])
        self.assertFalse(artifact["physical_drop_authorized"])
        self.assertEqual(
            set(artifact["must_record"]),
            {
                "production_archive_transaction_id",
                "production_archive_committed_at",
                "artifact_commit_deadline_at",
            },
        )
        self.assertTrue(
            all(self.contract["execution_preconditions"].values())
        )
        self.assertNotIn("DROP TABLE", self.forward.upper())
        self.assertNotIn("DROP TABLE", self.rollback.upper())
        self.assertNotIn("pg_xact_commit_timestamp", self.forward)
        self.assertNotIn("pg_xact_commit_timestamp", self.rollback)
        self.assertNotIn("track_commit_timestamp", self.forward)
        self.assertNotIn("track_commit_timestamp", self.rollback)
        self.assertIn("conservative_deadline_at", self.rollback)
        self.assertNotIn("\\ir sql/081_", self.rollback)
        self.assertNotIn("\\ir sql/073_", self.rollback)

    def test_forward_and_rollback_preserve_full_fixture_with_optional_functions(
        self,
    ) -> None:
        for optional_functions in (False, True):
            with self.subTest(optional_functions=optional_functions):
                self._run_round_trip(optional_functions=optional_functions)

    def _run_round_trip(self, *, optional_functions: bool) -> None:
        with _temporary_postgres() as postgres:
            postgres.sql(
                """
                CREATE ROLE n6_btrack_web LOGIN NOINHERIT;
                CREATE ROLE n6_virtual_executor LOGIN NOINHERIT;
                """,
                database="postgres",
                user="cluster_admin",
            )
            fixture = fixture_sql(optional_functions=optional_functions)
            fixture = fixture.replace(
                "CREATE ROLE n6_btrack_web LOGIN NOINHERIT;", ""
            ).replace(
                "CREATE ROLE n6_virtual_executor LOGIN NOINHERIT;", ""
            )
            postgres.sql(fixture)
            self.assertEqual(postgres.scalar("SHOW track_commit_timestamp"), "off")

            protected_before = postgres.scalar(protected_fingerprint_sql())
            strategy_probe = postgres.sql(strategy_fingerprint_sql(), check=False)
            if strategy_probe.returncode != 0:
                self.fail(
                    "strategy fingerprint preflight failed:\n"
                    f"stdout={strategy_probe.stdout}\n"
                    f"stderr={strategy_probe.stderr}"
                )
            strategy_before = postgres.scalar(strategy_fingerprint_sql())
            foreign_keys_before = postgres.scalar(
                """
                SELECT pg_catalog.count(*)
                FROM pg_catalog.pg_constraint constraint_row
                JOIN pg_catalog.pg_class relation
                  ON relation.oid = constraint_row.conrelid
                JOIN pg_catalog.pg_namespace namespace
                  ON namespace.oid = relation.relnamespace
                WHERE namespace.nspname = 'public'
                  AND relation.relname = ANY (
                    ARRAY[
                      'n6_strategy_package_catalog',
                      'n6_user_strategy_selection_revision',
                      'n6_user_strategy_selection_item',
                      'n6_strategy_match_projection',
                      'n6_strategy_observation_projection',
                      'n6_strategy_match_change'
                    ]
                  )
                  AND constraint_row.contype = 'f'
                """
            )
            self.assertTrue(protected_before)
            self.assertTrue(strategy_before)

            postgres.file(FORWARD)

            archived_counts = json.loads(
                postgres.scalar(
                    """
                    SELECT pg_catalog.jsonb_object_agg(
                      snapshot.table_name, snapshot.row_count
                      ORDER BY snapshot.table_name
                    )
                    FROM n6_strategy_center_archive_30d.table_snapshot snapshot
                    """
                )
            )
            self.assertEqual(archived_counts, EXPECTED_COUNTS)
            self.assertEqual(
                postgres.scalar(
                    """
                    SELECT (
                      pg_catalog.count(*) = 6
                      AND pg_catalog.bool_and(
                        pg_catalog.to_regclass(
                          'public.' || snapshot.table_name
                        ) IS NULL
                        AND pg_catalog.to_regclass(
                          'n6_strategy_center_archive_30d.'
                          || snapshot.table_name
                        ) IS NOT NULL
                      )
                    )::text
                    FROM n6_strategy_center_archive_30d.table_snapshot snapshot
                    """
                ),
                "true",
            )
            self.assertEqual(
                postgres.scalar(
                    """
                    SELECT (
                      pg_catalog.count(*) = 6
                      AND pg_catalog.bool_and(
                        pg_catalog.pg_get_userbyid(relation.relowner)
                          = snapshot.owner_name
                      )
                    )::text
                    FROM pg_catalog.pg_class relation
                    JOIN pg_catalog.pg_namespace namespace
                      ON namespace.oid = relation.relnamespace
                    JOIN n6_strategy_center_archive_30d.table_snapshot snapshot
                      ON snapshot.table_name = relation.relname
                    WHERE namespace.nspname =
                      'n6_strategy_center_archive_30d'
                      AND relation.relname = ANY (
                        ARRAY[
                          'n6_strategy_package_catalog',
                          'n6_user_strategy_selection_revision',
                          'n6_user_strategy_selection_item',
                          'n6_strategy_match_projection',
                          'n6_strategy_observation_projection',
                          'n6_strategy_match_change'
                        ]
                      )
                    """
                ),
                "true",
            )
            self.assertEqual(
                postgres.scalar(
                    """
                    SELECT pg_catalog.count(*)
                    FROM pg_catalog.pg_constraint constraint_row
                    JOIN pg_catalog.pg_class relation
                      ON relation.oid = constraint_row.conrelid
                    JOIN pg_catalog.pg_namespace namespace
                      ON namespace.oid = relation.relnamespace
                    WHERE namespace.nspname =
                      'n6_strategy_center_archive_30d'
                      AND relation.relname = ANY (
                        ARRAY[
                          'n6_strategy_package_catalog',
                          'n6_user_strategy_selection_revision',
                          'n6_user_strategy_selection_item',
                          'n6_strategy_match_projection',
                          'n6_strategy_observation_projection',
                          'n6_strategy_match_change'
                        ]
                      )
                      AND constraint_row.contype = 'f'
                    """
                ),
                foreign_keys_before,
            )
            expected_function_count = 9 if optional_functions else 7
            self.assertEqual(
                int(
                    postgres.scalar(
                        """
                        SELECT pg_catalog.count(*)
                        FROM n6_strategy_center_archive_30d.function_snapshot
                        """
                    )
                ),
                expected_function_count,
            )
            self.assertEqual(
                postgres.scalar(
                    """
                    SELECT (
                      NOT pg_catalog.has_schema_privilege(
                        'n6_btrack_web',
                        'n6_strategy_center_archive_30d',
                        'USAGE'
                      )
                      AND NOT pg_catalog.has_schema_privilege(
                        'n6_strategy_worker',
                        'n6_strategy_center_archive_30d',
                        'USAGE'
                      )
                      AND NOT pg_catalog.has_schema_privilege(
                        'n6_virtual_executor',
                        'n6_strategy_center_archive_30d',
                        'USAGE'
                      )
                    )::text
                    """
                ),
                "true",
            )
            self.assertEqual(
                postgres.scalar(
                    """
                    SELECT (
                      retention_anchor_at IS NOT NULL
                      AND conservative_deadline_at =
                        retention_anchor_at
                        + pg_catalog.make_interval(days => 30)
                      AND automatic_drop = false
                    )::text
                    FROM n6_strategy_center_archive_30d.archive_manifest
                    """
                ),
                "true",
            )
            self.assertEqual(
                postgres.scalar(protected_fingerprint_sql()),
                protected_before,
            )

            postgres.file(ROLLBACK)

            self.assertEqual(
                postgres.scalar(strategy_fingerprint_sql()),
                strategy_before,
            )
            self.assertEqual(
                postgres.scalar(protected_fingerprint_sql()),
                protected_before,
            )
            self.assertEqual(
                postgres.scalar(
                    """
                    SELECT (rolled_back_at IS NOT NULL)::text
                    FROM n6_strategy_center_archive_30d.archive_manifest
                    """
                ),
                "true",
            )

    def test_missing_core_function_fails_closed_without_partial_archive(self) -> None:
        with _temporary_postgres() as postgres:
            postgres.sql(
                """
                CREATE ROLE n6_btrack_web LOGIN NOINHERIT;
                CREATE ROLE n6_virtual_executor LOGIN NOINHERIT;
                """,
                database="postgres",
                user="cluster_admin",
            )
            fixture = fixture_sql(optional_functions=False)
            fixture = fixture.replace(
                "CREATE ROLE n6_btrack_web LOGIN NOINHERIT;", ""
            ).replace(
                "CREATE ROLE n6_virtual_executor LOGIN NOINHERIT;", ""
            )
            postgres.sql(fixture)
            postgres.sql(
                """
                DROP FUNCTION
                  public.n6_strategy_center_abandon_pending_v2(
                    bigint,text,bigint,bigint,bigint,date,text
                  )
                """
            )

            result = postgres.file(FORWARD, check=False)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("087 required function missing", result.stderr)
            self.assertEqual(
                postgres.scalar(
                    """
                    SELECT (
                      pg_catalog.to_regnamespace(
                        'n6_strategy_center_archive_30d'
                      ) IS NULL
                      AND pg_catalog.to_regclass(
                        'public.n6_strategy_match_projection'
                      ) IS NOT NULL
                    )::text
                    """
                ),
                "true",
            )


if __name__ == "__main__":
    unittest.main()
