-- A-share monitor v3 condition layer schema draft.
-- Stage N2-A only: review before running in any PostgreSQL database.
-- Boundary: condition eligibility only; no downstream runtime or trading tables.
-- Date convention: for_trade_date is the next trading day served by conditions;
-- source_trade_date is the finalized ingestion date and must equal prev_trade_date.

BEGIN;

CREATE TABLE common_condition_run (
  run_id TEXT PRIMARY KEY,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  source_version TEXT NOT NULL,
  source_versions JSONB NOT NULL DEFAULT '{}'::JSONB,
  source_ready_check JSONB,
  input_ingest_batch_id TEXT REFERENCES common_ingest_batch(batch_id),
  mode TEXT NOT NULL DEFAULT 'dry_run' CHECK (mode IN ('dry_run', 'execute')),
  status TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'running', 'passed', 'passed_active', 'failed', 'blocked', 'superseded', 'rolled_back')),
  p0_count INTEGER NOT NULL DEFAULT 0 CHECK (p0_count >= 0),
  p1_count INTEGER NOT NULL DEFAULT 0 CHECK (p1_count >= 0),
  p2_count INTEGER NOT NULL DEFAULT 0 CHECK (p2_count >= 0),
  generated_by TEXT NOT NULL DEFAULT 'condition_layer',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (finished_at IS NULL OR finished_at >= started_at),
  CHECK (mode <> 'execute' OR p0_count = 0 OR status = 'blocked')
);

CREATE INDEX idx_common_condition_run_for_trade_date
ON common_condition_run(for_trade_date, status);

CREATE INDEX idx_common_condition_run_source_version
ON common_condition_run(source_version);

CREATE INDEX idx_common_condition_run_source_trade_date
ON common_condition_run(source_trade_date);

CREATE UNIQUE INDEX ux_common_condition_run_one_passed_active
ON common_condition_run(source_trade_date, for_trade_date)
WHERE status = 'passed_active';

CREATE TABLE common_condition_quality_item (
  quality_item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  data_domain TEXT NOT NULL CHECK (data_domain IN ('common', 'stock', 'index', 'board')),
  layer_scope TEXT NOT NULL CHECK (layer_scope IN ('monitor_target', 'condition_basis', 'condition_pool', 'minute_target_scope', 'condition_run')),
  table_name TEXT,
  gate_code TEXT NOT NULL,
  gate_name TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('P0', 'P1', 'P2')),
  status TEXT NOT NULL CHECK (status IN ('passed', 'failed', 'warning', 'skipped')),
  expected_value TEXT,
  actual_value TEXT,
  identity_key TEXT,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$')
);

CREATE INDEX idx_common_condition_quality_run
ON common_condition_quality_item(run_id);

CREATE INDEX idx_common_condition_quality_status
ON common_condition_quality_item(status, severity);

CREATE INDEX idx_common_condition_quality_domain_scope
ON common_condition_quality_item(data_domain, layer_scope, source_trade_date, for_trade_date);

CREATE TABLE stock_monitor_target (
  stock_monitor_target_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  stock_identity_key TEXT NOT NULL REFERENCES stock_identity(stock_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ')),
  name TEXT NOT NULL,
  monitor_type TEXT NOT NULL CHECK (monitor_type IN ('stock_buy_monitor', 'stock_sell_monitor', 'open_position', 'stock_hint_monitor', 'manual_watch')),
  lane TEXT NOT NULL CHECK (lane IN ('stock_trade', 'stock_alert')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'disabled', 'expired')),
  direction_scope TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  source TEXT NOT NULL,
  source_version TEXT NOT NULL,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(for_trade_date, stock_identity_key, lane, monitor_type, source_version),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (stock_identity_key = 'stock:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (code !~ '^88[0-9]{4}$'),
  CHECK (direction_scope <@ ARRAY['buy', 'sell']::TEXT[]),
  CHECK (
    (lane = 'stock_trade' AND direction_scope <@ ARRAY['buy', 'sell']::TEXT[])
    OR lane = 'stock_alert'
  ),
  CHECK (lane <> 'stock_trade' OR monitor_type IN ('stock_buy_monitor', 'stock_sell_monitor', 'open_position')),
  CHECK (monitor_type <> 'stock_buy_monitor' OR direction_scope <@ ARRAY['buy']::TEXT[]),
  CHECK (monitor_type NOT IN ('stock_sell_monitor', 'open_position') OR direction_scope <@ ARRAY['sell']::TEXT[])
);

CREATE INDEX idx_stock_monitor_target_date_status
ON stock_monitor_target(for_trade_date, status, lane);

CREATE INDEX idx_stock_monitor_target_identity
ON stock_monitor_target(stock_identity_key, for_trade_date);

CREATE TABLE index_monitor_target (
  index_monitor_target_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  index_identity_key TEXT NOT NULL REFERENCES index_identity(index_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ', 'CSI', 'CNI', 'SW', 'TDX', 'OTH', 'UNKNOWN')),
  name TEXT NOT NULL,
  monitor_type TEXT NOT NULL CHECK (monitor_type IN ('index_monitor', 'index_hint_monitor', 'market_watch')),
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'disabled', 'expired')),
  direction_scope TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  source TEXT NOT NULL,
  source_version TEXT NOT NULL,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(for_trade_date, index_identity_key, monitor_type, source_version),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (index_identity_key = 'index:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (direction_scope <@ ARRAY['buy', 'sell']::TEXT[])
);

CREATE INDEX idx_index_monitor_target_date_status
ON index_monitor_target(for_trade_date, status, lane);

CREATE INDEX idx_index_monitor_target_identity
ON index_monitor_target(index_identity_key, for_trade_date);

CREATE TABLE board_monitor_target (
  board_monitor_target_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  board_identity_key TEXT NOT NULL REFERENCES board_identity(board_identity_key),
  board_code TEXT NOT NULL,
  board_name TEXT NOT NULL,
  board_type TEXT NOT NULL CHECK (board_type IN ('tdx_region', 'tdx_concept', 'tdx_industry', 'tdx_other')),
  monitor_type TEXT NOT NULL CHECK (monitor_type IN ('board_monitor', 'board_hint_monitor', 'market_watch')),
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'disabled', 'expired')),
  direction_scope TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  source TEXT NOT NULL,
  source_version TEXT NOT NULL,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(for_trade_date, board_identity_key, monitor_type, source_version),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (board_identity_key = 'board:TDX:' || board_code),
  CHECK (board_code ~ '^88[0-9]{4}$'),
  CHECK (direction_scope <@ ARRAY['buy', 'sell']::TEXT[])
);

CREATE INDEX idx_board_monitor_target_date_status
ON board_monitor_target(for_trade_date, status, lane);

CREATE INDEX idx_board_monitor_target_identity
ON board_monitor_target(board_identity_key, for_trade_date);

CREATE TABLE stock_condition_basis (
  stock_condition_basis_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  stock_identity_key TEXT NOT NULL REFERENCES stock_identity(stock_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ')),
  name TEXT NOT NULL,
  is_st BOOLEAN NOT NULL DEFAULT false,
  stock_status TEXT NOT NULL DEFAULT 'active' CHECK (stock_status IN ('active', 'delisted', 'paused', 'unknown')),
  official_daily_proof BOOLEAN NOT NULL DEFAULT false,
  lane TEXT NOT NULL CHECK (lane IN ('stock_trade', 'stock_alert')),
  monitor_type TEXT NOT NULL,
  monitor_status TEXT NOT NULL CHECK (monitor_status IN ('active', 'paused', 'disabled', 'expired')),
  direction_scope TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  source_monitor_target_id BIGINT NOT NULL REFERENCES stock_monitor_target(stock_monitor_target_id),
  period_key_y TEXT,
  period_key_q TEXT,
  period_key_m TEXT,
  period_key_w TEXT,
  period_key_d TEXT,
  period_grade_y TEXT,
  period_grade_q TEXT,
  period_grade_m TEXT,
  period_grade_w TEXT,
  period_grade_d TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  amount_day NUMERIC,
  amount_prev_day NUMERIC,
  amount_week NUMERIC,
  amount_prev_week NUMERIC,
  amount_month NUMERIC,
  amount_prev_month NUMERIC,
  amount_quarter NUMERIC,
  amount_prev_quarter NUMERIC,
  amount_year NUMERIC,
  amount_prev_year NUMERIC,
  amount_source TEXT,
  amount_quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (amount_quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  period_trigger_baseline_json JSONB,
  main_up_anchor TEXT CHECK (main_up_anchor IS NULL OR main_up_anchor IN ('Y', 'Q', 'M', 'W')),
  up_reference_period TEXT CHECK (up_reference_period IS NULL OR up_reference_period IN ('Q', 'M', 'W', 'D')),
  up_amplitude NUMERIC,
  up_base_price NUMERIC,
  buy_target_price NUMERIC,
  buy_expected_return_pct NUMERIC,
  up_trend_start_date TEXT,
  up_trend_end_date TEXT,
  up_reference_window_start TEXT,
  up_reference_window_end TEXT,
  main_down_anchor TEXT CHECK (main_down_anchor IS NULL OR main_down_anchor IN ('Y', 'Q', 'M', 'W')),
  down_reference_period TEXT CHECK (down_reference_period IS NULL OR down_reference_period IN ('Q', 'M', 'W', 'D')),
  down_amplitude NUMERIC,
  down_base_price NUMERIC,
  sell_target_price NUMERIC,
  sell_expected_return_pct NUMERIC,
  down_trend_start_date TEXT,
  down_trend_end_date TEXT,
  down_reference_window_start TEXT,
  down_reference_window_end TEXT,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  pe_core NUMERIC,
  total_mv NUMERIC,
  circ_mv NUMERIC,
  score NUMERIC,
  recommendation_level TEXT,
  recommendation_reason TEXT,
  financial_asof_date TEXT,
  financial_quality_status TEXT CHECK (financial_quality_status IS NULL OR financial_quality_status IN ('passed', 'warning', 'failed')),
  cash_realization_rate NUMERIC,
  revenue_yoy_pct NUMERIC,
  core_profit_yoy_pct NUMERIC,
  report_core_revenue NUMERIC,
  report_core_profit NUMERIC,
  core_profit_ttm NUMERIC,
  core_gt_revenue_yoy BOOLEAN,
  revenue_growth_streak_q INTEGER,
  core_growth_streak_q INTEGER,
  core_gt_revenue_streak_q INTEGER,
  forecast_type TEXT,
  forecast_score NUMERIC,
  score_breakdown_json JSONB,
  financial_warning_json JSONB,
  financial_metric_version TEXT,
  financial_source_version TEXT,
  main_index_identity_key TEXT REFERENCES index_identity(index_identity_key),
  main_index_code TEXT,
  main_index_name TEXT,
  main_index_expected_return_pct NUMERIC,
  preferred_board_identity_key TEXT REFERENCES board_identity(board_identity_key),
  preferred_board_code TEXT,
  preferred_board_name TEXT,
  preferred_board_expected_return_pct NUMERIC,
  linked_board_identity_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  buy_necessary_base BOOLEAN NOT NULL DEFAULT false,
  buy_necessary_key TEXT,
  buy_necessary_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  sell_necessary_base BOOLEAN NOT NULL DEFAULT false,
  sell_necessary_key TEXT,
  sell_necessary_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  buy_full_necessary_base BOOLEAN NOT NULL DEFAULT false,
  buy_full_necessary_key TEXT,
  sell_full_necessary_base BOOLEAN NOT NULL DEFAULT false,
  sell_full_necessary_key TEXT,
  oversold_hint_necessary_base BOOLEAN NOT NULL DEFAULT false,
  oversold_hint_key TEXT,
  overbought_hint_necessary_base BOOLEAN NOT NULL DEFAULT false,
  overbought_hint_key TEXT,
  source_version TEXT NOT NULL,
  source_batch_id TEXT REFERENCES common_ingest_batch(batch_id),
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, stock_identity_key, lane, monitor_type),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (stock_identity_key = 'stock:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (code !~ '^88[0-9]{4}$'),
  CHECK (direction_scope <@ ARRAY['buy', 'sell']::TEXT[]),
  CHECK (buy_necessary_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (sell_necessary_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (period_key_d IS NULL OR period_key_d = prev_trade_date),
  CHECK (up_trend_start_date IS NULL OR up_trend_start_date ~ '^[0-9]{8}$'),
  CHECK (up_trend_end_date IS NULL OR up_trend_end_date ~ '^[0-9]{8}$'),
  CHECK (up_reference_window_start IS NULL OR up_reference_window_start ~ '^[0-9]{8}$'),
  CHECK (up_reference_window_end IS NULL OR up_reference_window_end ~ '^[0-9]{8}$'),
  CHECK (down_trend_start_date IS NULL OR down_trend_start_date ~ '^[0-9]{8}$'),
  CHECK (down_trend_end_date IS NULL OR down_trend_end_date ~ '^[0-9]{8}$'),
  CHECK (down_reference_window_start IS NULL OR down_reference_window_start ~ '^[0-9]{8}$'),
  CHECK (down_reference_window_end IS NULL OR down_reference_window_end ~ '^[0-9]{8}$'),
  CHECK (financial_asof_date IS NULL OR financial_asof_date ~ '^[0-9]{8}$'),
  CHECK (buy_full_necessary_key IS NULL OR buy_full_necessary_key = 'BUY:FULL'),
  CHECK (sell_full_necessary_key IS NULL OR sell_full_necessary_key = 'SELL:FULL'),
  CHECK (oversold_hint_key IS NULL OR oversold_hint_key = 'BUY_HINT'),
  CHECK (overbought_hint_key IS NULL OR overbought_hint_key = 'SELL_HINT'),
  CHECK (period_grade_y IS NULL OR period_grade_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_q IS NULL OR period_grade_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_m IS NULL OR period_grade_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_w IS NULL OR period_grade_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_d IS NULL OR period_grade_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown'))
);

CREATE INDEX idx_stock_condition_basis_run
ON stock_condition_basis(run_id);

CREATE INDEX idx_stock_condition_basis_date_lane
ON stock_condition_basis(for_trade_date, source_trade_date, lane, quality_status);

CREATE INDEX idx_stock_condition_basis_identity
ON stock_condition_basis(stock_identity_key, for_trade_date);

CREATE TABLE index_condition_basis (
  index_condition_basis_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  index_identity_key TEXT NOT NULL REFERENCES index_identity(index_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ', 'CSI', 'CNI', 'SW', 'TDX', 'OTH', 'UNKNOWN')),
  name TEXT NOT NULL,
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  monitor_type TEXT NOT NULL,
  monitor_status TEXT NOT NULL CHECK (monitor_status IN ('active', 'paused', 'disabled', 'expired')),
  direction_scope TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  source_monitor_target_id BIGINT NOT NULL REFERENCES index_monitor_target(index_monitor_target_id),
  period_key_y TEXT,
  period_key_q TEXT,
  period_key_m TEXT,
  period_key_w TEXT,
  period_key_d TEXT,
  period_grade_y TEXT,
  period_grade_q TEXT,
  period_grade_m TEXT,
  period_grade_w TEXT,
  period_grade_d TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  amount_day NUMERIC,
  amount_prev_day NUMERIC,
  amount_week NUMERIC,
  amount_prev_week NUMERIC,
  amount_month NUMERIC,
  amount_prev_month NUMERIC,
  amount_quarter NUMERIC,
  amount_prev_quarter NUMERIC,
  amount_year NUMERIC,
  amount_prev_year NUMERIC,
  amount_source TEXT,
  amount_quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (amount_quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  period_trigger_baseline_json JSONB,
  main_up_anchor TEXT CHECK (main_up_anchor IS NULL OR main_up_anchor IN ('Y', 'Q', 'M', 'W')),
  up_reference_period TEXT CHECK (up_reference_period IS NULL OR up_reference_period IN ('Q', 'M', 'W', 'D')),
  up_amplitude NUMERIC,
  up_base_price NUMERIC,
  buy_target_price NUMERIC,
  buy_expected_return_pct NUMERIC,
  up_trend_start_date TEXT,
  up_trend_end_date TEXT,
  up_reference_window_start TEXT,
  up_reference_window_end TEXT,
  main_down_anchor TEXT CHECK (main_down_anchor IS NULL OR main_down_anchor IN ('Y', 'Q', 'M', 'W')),
  down_reference_period TEXT CHECK (down_reference_period IS NULL OR down_reference_period IN ('Q', 'M', 'W', 'D')),
  down_amplitude NUMERIC,
  down_base_price NUMERIC,
  sell_target_price NUMERIC,
  sell_expected_return_pct NUMERIC,
  down_trend_start_date TEXT,
  down_trend_end_date TEXT,
  down_reference_window_start TEXT,
  down_reference_window_end TEXT,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  buy_necessary_base BOOLEAN NOT NULL DEFAULT false,
  buy_necessary_key TEXT,
  buy_necessary_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  sell_necessary_base BOOLEAN NOT NULL DEFAULT false,
  sell_necessary_key TEXT,
  sell_necessary_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  buy_full_necessary_base BOOLEAN NOT NULL DEFAULT false,
  buy_full_necessary_key TEXT,
  sell_full_necessary_base BOOLEAN NOT NULL DEFAULT false,
  sell_full_necessary_key TEXT,
  oversold_hint_necessary_base BOOLEAN NOT NULL DEFAULT false,
  oversold_hint_key TEXT,
  overbought_hint_necessary_base BOOLEAN NOT NULL DEFAULT false,
  overbought_hint_key TEXT,
  source_version TEXT NOT NULL,
  source_batch_id TEXT REFERENCES common_ingest_batch(batch_id),
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, index_identity_key, monitor_type),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (index_identity_key = 'index:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (direction_scope <@ ARRAY['buy', 'sell']::TEXT[]),
  CHECK (buy_necessary_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (sell_necessary_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (period_key_d IS NULL OR period_key_d = prev_trade_date),
  CHECK (up_trend_start_date IS NULL OR up_trend_start_date ~ '^[0-9]{8}$'),
  CHECK (up_trend_end_date IS NULL OR up_trend_end_date ~ '^[0-9]{8}$'),
  CHECK (up_reference_window_start IS NULL OR up_reference_window_start ~ '^[0-9]{8}$'),
  CHECK (up_reference_window_end IS NULL OR up_reference_window_end ~ '^[0-9]{8}$'),
  CHECK (down_trend_start_date IS NULL OR down_trend_start_date ~ '^[0-9]{8}$'),
  CHECK (down_trend_end_date IS NULL OR down_trend_end_date ~ '^[0-9]{8}$'),
  CHECK (down_reference_window_start IS NULL OR down_reference_window_start ~ '^[0-9]{8}$'),
  CHECK (down_reference_window_end IS NULL OR down_reference_window_end ~ '^[0-9]{8}$'),
  CHECK (buy_full_necessary_key IS NULL OR buy_full_necessary_key = 'BUY:FULL'),
  CHECK (sell_full_necessary_key IS NULL OR sell_full_necessary_key = 'SELL:FULL'),
  CHECK (oversold_hint_key IS NULL OR oversold_hint_key = 'BUY_HINT'),
  CHECK (overbought_hint_key IS NULL OR overbought_hint_key = 'SELL_HINT'),
  CHECK (period_grade_y IS NULL OR period_grade_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_q IS NULL OR period_grade_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_m IS NULL OR period_grade_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_w IS NULL OR period_grade_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_d IS NULL OR period_grade_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown'))
);

CREATE INDEX idx_index_condition_basis_run
ON index_condition_basis(run_id);

CREATE INDEX idx_index_condition_basis_date_lane
ON index_condition_basis(for_trade_date, source_trade_date, lane, quality_status);

CREATE INDEX idx_index_condition_basis_identity
ON index_condition_basis(index_identity_key, for_trade_date);

CREATE TABLE board_condition_basis (
  board_condition_basis_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  board_identity_key TEXT NOT NULL REFERENCES board_identity(board_identity_key),
  board_code TEXT NOT NULL,
  board_name TEXT NOT NULL,
  board_type TEXT NOT NULL CHECK (board_type IN ('tdx_region', 'tdx_concept', 'tdx_industry', 'tdx_other')),
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  monitor_type TEXT NOT NULL,
  monitor_status TEXT NOT NULL CHECK (monitor_status IN ('active', 'paused', 'disabled', 'expired')),
  direction_scope TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  source_monitor_target_id BIGINT NOT NULL REFERENCES board_monitor_target(board_monitor_target_id),
  period_key_y TEXT,
  period_key_q TEXT,
  period_key_m TEXT,
  period_key_w TEXT,
  period_key_d TEXT,
  period_grade_y TEXT,
  period_grade_q TEXT,
  period_grade_m TEXT,
  period_grade_w TEXT,
  period_grade_d TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  amount_day NUMERIC,
  amount_prev_day NUMERIC,
  amount_week NUMERIC,
  amount_prev_week NUMERIC,
  amount_month NUMERIC,
  amount_prev_month NUMERIC,
  amount_quarter NUMERIC,
  amount_prev_quarter NUMERIC,
  amount_year NUMERIC,
  amount_prev_year NUMERIC,
  amount_source TEXT,
  amount_quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (amount_quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  period_trigger_baseline_json JSONB,
  main_up_anchor TEXT CHECK (main_up_anchor IS NULL OR main_up_anchor IN ('Y', 'Q', 'M', 'W')),
  up_reference_period TEXT CHECK (up_reference_period IS NULL OR up_reference_period IN ('Q', 'M', 'W', 'D')),
  up_amplitude NUMERIC,
  up_base_price NUMERIC,
  buy_target_price NUMERIC,
  buy_expected_return_pct NUMERIC,
  up_trend_start_date TEXT,
  up_trend_end_date TEXT,
  up_reference_window_start TEXT,
  up_reference_window_end TEXT,
  main_down_anchor TEXT CHECK (main_down_anchor IS NULL OR main_down_anchor IN ('Y', 'Q', 'M', 'W')),
  down_reference_period TEXT CHECK (down_reference_period IS NULL OR down_reference_period IN ('Q', 'M', 'W', 'D')),
  down_amplitude NUMERIC,
  down_base_price NUMERIC,
  sell_target_price NUMERIC,
  sell_expected_return_pct NUMERIC,
  down_trend_start_date TEXT,
  down_trend_end_date TEXT,
  down_reference_window_start TEXT,
  down_reference_window_end TEXT,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  buy_necessary_base BOOLEAN NOT NULL DEFAULT false,
  buy_necessary_key TEXT,
  buy_necessary_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  sell_necessary_base BOOLEAN NOT NULL DEFAULT false,
  sell_necessary_key TEXT,
  sell_necessary_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  buy_full_necessary_base BOOLEAN NOT NULL DEFAULT false,
  buy_full_necessary_key TEXT,
  sell_full_necessary_base BOOLEAN NOT NULL DEFAULT false,
  sell_full_necessary_key TEXT,
  oversold_hint_necessary_base BOOLEAN NOT NULL DEFAULT false,
  oversold_hint_key TEXT,
  overbought_hint_necessary_base BOOLEAN NOT NULL DEFAULT false,
  overbought_hint_key TEXT,
  source_version TEXT NOT NULL,
  source_batch_id TEXT REFERENCES common_ingest_batch(batch_id),
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, board_identity_key, monitor_type),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (board_identity_key = 'board:TDX:' || board_code),
  CHECK (board_code ~ '^88[0-9]{4}$'),
  CHECK (direction_scope <@ ARRAY['buy', 'sell']::TEXT[]),
  CHECK (buy_necessary_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (sell_necessary_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (period_key_d IS NULL OR period_key_d = prev_trade_date),
  CHECK (up_trend_start_date IS NULL OR up_trend_start_date ~ '^[0-9]{8}$'),
  CHECK (up_trend_end_date IS NULL OR up_trend_end_date ~ '^[0-9]{8}$'),
  CHECK (up_reference_window_start IS NULL OR up_reference_window_start ~ '^[0-9]{8}$'),
  CHECK (up_reference_window_end IS NULL OR up_reference_window_end ~ '^[0-9]{8}$'),
  CHECK (down_trend_start_date IS NULL OR down_trend_start_date ~ '^[0-9]{8}$'),
  CHECK (down_trend_end_date IS NULL OR down_trend_end_date ~ '^[0-9]{8}$'),
  CHECK (down_reference_window_start IS NULL OR down_reference_window_start ~ '^[0-9]{8}$'),
  CHECK (down_reference_window_end IS NULL OR down_reference_window_end ~ '^[0-9]{8}$'),
  CHECK (buy_full_necessary_key IS NULL OR buy_full_necessary_key = 'BUY:FULL'),
  CHECK (sell_full_necessary_key IS NULL OR sell_full_necessary_key = 'SELL:FULL'),
  CHECK (oversold_hint_key IS NULL OR oversold_hint_key = 'BUY_HINT'),
  CHECK (overbought_hint_key IS NULL OR overbought_hint_key = 'SELL_HINT'),
  CHECK (period_grade_y IS NULL OR period_grade_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_q IS NULL OR period_grade_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_m IS NULL OR period_grade_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_w IS NULL OR period_grade_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_d IS NULL OR period_grade_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown'))
);

CREATE INDEX idx_board_condition_basis_run
ON board_condition_basis(run_id);

CREATE INDEX idx_board_condition_basis_date_lane
ON board_condition_basis(for_trade_date, source_trade_date, lane, quality_status);

CREATE INDEX idx_board_condition_basis_identity
ON board_condition_basis(board_identity_key, for_trade_date);

CREATE TABLE stock_condition_pool (
  stock_condition_pool_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  stock_identity_key TEXT NOT NULL REFERENCES stock_identity(stock_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ')),
  name TEXT NOT NULL,
  lane TEXT NOT NULL CHECK (lane IN ('stock_trade', 'stock_alert')),
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_date TEXT,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  minute_scope_reason TEXT,
  market_data_consumer TEXT NOT NULL DEFAULT 'trigger_daily_snapshot' CHECK (market_data_consumer IN ('trigger_daily_snapshot', 'action_minute_bar', 'both')),
  monitor_type TEXT NOT NULL,
  policy_name TEXT NOT NULL,
  policy_hash TEXT NOT NULL,
  selected_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  excluded_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  period_trigger_baseline_json JSONB,
  main_up_anchor TEXT CHECK (main_up_anchor IS NULL OR main_up_anchor IN ('Y', 'Q', 'M', 'W')),
  up_reference_period TEXT CHECK (up_reference_period IS NULL OR up_reference_period IN ('Q', 'M', 'W', 'D')),
  buy_target_price NUMERIC,
  buy_expected_return_pct NUMERIC,
  main_down_anchor TEXT CHECK (main_down_anchor IS NULL OR main_down_anchor IN ('Y', 'Q', 'M', 'W')),
  down_reference_period TEXT CHECK (down_reference_period IS NULL OR down_reference_period IN ('Q', 'M', 'W', 'D')),
  sell_target_price NUMERIC,
  sell_expected_return_pct NUMERIC,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  pe_core NUMERIC,
  score NUMERIC,
  financial_quality_status TEXT,
  cash_realization_rate NUMERIC,
  revenue_yoy_pct NUMERIC,
  core_profit_yoy_pct NUMERIC,
  report_core_revenue NUMERIC,
  report_core_profit NUMERIC,
  core_profit_ttm NUMERIC,
  core_gt_revenue_yoy BOOLEAN,
  revenue_growth_streak_q INTEGER,
  core_growth_streak_q INTEGER,
  core_gt_revenue_streak_q INTEGER,
  forecast_type TEXT,
  forecast_score NUMERIC,
  score_breakdown_json JSONB,
  financial_warning_json JSONB,
  financial_metric_version TEXT,
  recommendation_level TEXT,
  recommendation_reason TEXT,
  main_index_identity_key TEXT REFERENCES index_identity(index_identity_key),
  main_index_code TEXT,
  main_index_name TEXT,
  main_index_expected_return_pct NUMERIC,
  preferred_board_identity_key TEXT REFERENCES board_identity(board_identity_key),
  preferred_board_code TEXT,
  preferred_board_name TEXT,
  preferred_board_expected_return_pct NUMERIC,
  linked_board_identity_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  source_condition_basis_id BIGINT NOT NULL REFERENCES stock_condition_basis(stock_condition_basis_id),
  source_version TEXT NOT NULL,
  active_target BOOLEAN NOT NULL DEFAULT true,
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, stock_identity_key, lane, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (stock_identity_key = 'stock:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (code !~ '^88[0-9]{4}$'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'),
  CHECK (allowed_signal_types <@ ARRAY['BUY', 'SELL', 'BUY:FULL', 'SELL:FULL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (previous_day_minute_required = false OR previous_day_minute_date = prev_trade_date),
  CHECK (previous_day_minute_quality_required = false OR previous_day_minute_required = true),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true)),
  CHECK (
    lane <> 'stock_trade'
    OR (monitor_type = 'stock_buy_monitor' AND direction = 'buy')
    OR (monitor_type IN ('stock_sell_monitor', 'open_position') AND direction = 'sell')
  )
);

CREATE INDEX idx_stock_condition_pool_run
ON stock_condition_pool(run_id);

CREATE INDEX idx_stock_condition_pool_date_lane_direction
ON stock_condition_pool(for_trade_date, source_trade_date, lane, direction, active_target);

CREATE INDEX idx_stock_condition_pool_basis
ON stock_condition_pool(source_condition_basis_id);

CREATE TABLE index_condition_pool (
  index_condition_pool_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  index_identity_key TEXT NOT NULL REFERENCES index_identity(index_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ', 'CSI', 'CNI', 'SW', 'TDX', 'OTH', 'UNKNOWN')),
  name TEXT NOT NULL,
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_date TEXT,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  minute_scope_reason TEXT,
  market_data_consumer TEXT NOT NULL DEFAULT 'trigger_daily_snapshot' CHECK (market_data_consumer IN ('trigger_daily_snapshot', 'action_minute_bar', 'both')),
  monitor_type TEXT NOT NULL,
  policy_name TEXT NOT NULL,
  policy_hash TEXT NOT NULL,
  selected_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  excluded_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  period_trigger_baseline_json JSONB,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  source_condition_basis_id BIGINT NOT NULL REFERENCES index_condition_basis(index_condition_basis_id),
  source_version TEXT NOT NULL,
  active_target BOOLEAN NOT NULL DEFAULT true,
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, index_identity_key, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (index_identity_key = 'index:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'),
  CHECK (allowed_signal_types <@ ARRAY['BUY', 'SELL', 'BUY:FULL', 'SELL:FULL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (previous_day_minute_required = false OR previous_day_minute_date = prev_trade_date),
  CHECK (previous_day_minute_quality_required = false OR previous_day_minute_required = true),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true))
);

CREATE INDEX idx_index_condition_pool_run
ON index_condition_pool(run_id);

CREATE INDEX idx_index_condition_pool_date_direction
ON index_condition_pool(for_trade_date, source_trade_date, direction, active_target);

CREATE INDEX idx_index_condition_pool_basis
ON index_condition_pool(source_condition_basis_id);

CREATE TABLE board_condition_pool (
  board_condition_pool_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  board_identity_key TEXT NOT NULL REFERENCES board_identity(board_identity_key),
  board_code TEXT NOT NULL,
  board_name TEXT NOT NULL,
  board_type TEXT NOT NULL CHECK (board_type IN ('tdx_region', 'tdx_concept', 'tdx_industry', 'tdx_other')),
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_date TEXT,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  minute_scope_reason TEXT,
  market_data_consumer TEXT NOT NULL DEFAULT 'trigger_daily_snapshot' CHECK (market_data_consumer IN ('trigger_daily_snapshot', 'action_minute_bar', 'both')),
  monitor_type TEXT NOT NULL,
  policy_name TEXT NOT NULL,
  policy_hash TEXT NOT NULL,
  selected_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  excluded_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  period_trigger_baseline_json JSONB,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  source_condition_basis_id BIGINT NOT NULL REFERENCES board_condition_basis(board_condition_basis_id),
  source_version TEXT NOT NULL,
  active_target BOOLEAN NOT NULL DEFAULT true,
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, board_identity_key, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (board_identity_key = 'board:TDX:' || board_code),
  CHECK (board_code ~ '^88[0-9]{4}$'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'),
  CHECK (allowed_signal_types <@ ARRAY['BUY', 'SELL', 'BUY:FULL', 'SELL:FULL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (previous_day_minute_required = false OR previous_day_minute_date = prev_trade_date),
  CHECK (previous_day_minute_quality_required = false OR previous_day_minute_required = true),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true))
);

CREATE INDEX idx_board_condition_pool_run
ON board_condition_pool(run_id);

CREATE INDEX idx_board_condition_pool_date_direction
ON board_condition_pool(for_trade_date, source_trade_date, direction, active_target);

CREATE INDEX idx_board_condition_pool_basis
ON board_condition_pool(source_condition_basis_id);

CREATE TABLE stock_minute_target_scope (
  stock_minute_target_scope_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  stock_identity_key TEXT NOT NULL REFERENCES stock_identity(stock_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ')),
  name TEXT NOT NULL,
  lane TEXT NOT NULL CHECK (lane IN ('stock_trade', 'stock_alert')),
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  scope_source TEXT NOT NULL DEFAULT 'condition_pool' CHECK (scope_source IN ('condition_pool')),
  source_condition_pool_id BIGINT NOT NULL REFERENCES stock_condition_pool(stock_condition_pool_id),
  reason TEXT,
  period_trigger_baseline_json JSONB,
  total_mv NUMERIC NOT NULL,
  market_value_threshold NUMERIC NOT NULL DEFAULT 1000000,
  pe_core NUMERIC,
  score NUMERIC,
  financial_quality_status TEXT,
  cash_realization_rate NUMERIC,
  revenue_yoy_pct NUMERIC,
  core_profit_yoy_pct NUMERIC,
  report_core_revenue NUMERIC,
  report_core_profit NUMERIC,
  core_profit_ttm NUMERIC,
  core_gt_revenue_yoy BOOLEAN,
  revenue_growth_streak_q INTEGER,
  core_growth_streak_q INTEGER,
  core_gt_revenue_streak_q INTEGER,
  forecast_type TEXT,
  forecast_score NUMERIC,
  score_breakdown_json JSONB,
  financial_warning_json JSONB,
  financial_metric_version TEXT,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_date TEXT,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  minute_scope_reason TEXT,
  market_data_consumer TEXT NOT NULL DEFAULT 'trigger_daily_snapshot' CHECK (market_data_consumer IN ('trigger_daily_snapshot', 'action_minute_bar', 'both')),
  source_version TEXT NOT NULL,
  scope_status TEXT NOT NULL DEFAULT 'planned' CHECK (scope_status IN ('planned', 'active', 'skipped', 'expired')),
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, stock_identity_key, lane, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (stock_identity_key = 'stock:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (code !~ '^88[0-9]{4}$'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'),
  CHECK (allowed_signal_types <@ ARRAY['BUY', 'SELL', 'BUY:FULL', 'SELL:FULL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (total_mv >= market_value_threshold),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (previous_day_minute_required = false OR previous_day_minute_date = prev_trade_date),
  CHECK (previous_day_minute_quality_required = false OR previous_day_minute_required = true),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true))
);

CREATE INDEX idx_stock_minute_scope_date_lane
ON stock_minute_target_scope(for_trade_date, source_trade_date, lane, direction, scope_status);

CREATE INDEX idx_stock_minute_scope_pool
ON stock_minute_target_scope(source_condition_pool_id);

CREATE TABLE index_minute_target_scope (
  index_minute_target_scope_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  index_identity_key TEXT NOT NULL REFERENCES index_identity(index_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ', 'CSI', 'CNI', 'SW', 'TDX', 'OTH', 'UNKNOWN')),
  name TEXT NOT NULL,
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  scope_source TEXT NOT NULL DEFAULT 'fixed_index_scope' CHECK (scope_source IN ('condition_pool', 'fixed_index_scope')),
  source_condition_pool_id BIGINT REFERENCES index_condition_pool(index_condition_pool_id),
  reason TEXT,
  period_trigger_baseline_json JSONB,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_date TEXT,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  minute_scope_reason TEXT,
  market_data_consumer TEXT NOT NULL DEFAULT 'trigger_daily_snapshot' CHECK (market_data_consumer IN ('trigger_daily_snapshot', 'action_minute_bar', 'both')),
  source_version TEXT NOT NULL,
  scope_status TEXT NOT NULL DEFAULT 'planned' CHECK (scope_status IN ('planned', 'active', 'skipped', 'expired')),
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, index_identity_key, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (index_identity_key = 'index:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (scope_source <> 'fixed_index_scope' OR code IN ('000905', '399303', '000001', '000852', '399001', '399006', '000300', '000016', '000688')),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (
    (scope_source = 'fixed_index_scope' AND condition_key IN ('FIXED_INDEX_SCOPE:BUY', 'FIXED_INDEX_SCOPE:SELL'))
    OR (
      scope_source = 'condition_pool'
      AND condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'
    )
  ),
  CHECK (allowed_signal_types <@ ARRAY['BUY', 'SELL', 'BUY:FULL', 'SELL:FULL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (scope_source <> 'condition_pool' OR source_condition_pool_id IS NOT NULL),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (previous_day_minute_required = false OR previous_day_minute_date = prev_trade_date),
  CHECK (previous_day_minute_quality_required = false OR previous_day_minute_required = true),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT|.*:BUY$)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT|.*:SELL$)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true))
);

CREATE INDEX idx_index_minute_scope_date
ON index_minute_target_scope(for_trade_date, source_trade_date, direction, scope_status);

CREATE INDEX idx_index_minute_scope_pool
ON index_minute_target_scope(source_condition_pool_id);

CREATE TABLE board_minute_target_scope (
  board_minute_target_scope_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  board_identity_key TEXT NOT NULL REFERENCES board_identity(board_identity_key),
  board_code TEXT NOT NULL,
  board_name TEXT NOT NULL,
  board_type TEXT NOT NULL CHECK (board_type IN ('tdx_region', 'tdx_concept', 'tdx_industry', 'tdx_other')),
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane IN ('market_alert')),
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  scope_source TEXT NOT NULL DEFAULT 'industry_board_scope' CHECK (scope_source IN ('condition_pool', 'industry_board_scope')),
  source_condition_pool_id BIGINT REFERENCES board_condition_pool(board_condition_pool_id),
  reason TEXT,
  period_trigger_baseline_json JSONB,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_date TEXT,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  minute_scope_reason TEXT,
  market_data_consumer TEXT NOT NULL DEFAULT 'trigger_daily_snapshot' CHECK (market_data_consumer IN ('trigger_daily_snapshot', 'action_minute_bar', 'both')),
  source_version TEXT NOT NULL,
  scope_status TEXT NOT NULL DEFAULT 'planned' CHECK (scope_status IN ('planned', 'active', 'skipped', 'expired')),
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, board_identity_key, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (board_identity_key = 'board:TDX:' || board_code),
  CHECK (board_code ~ '^88[0-9]{4}$'),
  CHECK (scope_source <> 'industry_board_scope' OR board_code LIKE '881%'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (
    (scope_source = 'industry_board_scope' AND condition_key IN ('INDUSTRY_BOARD_SCOPE:BUY', 'INDUSTRY_BOARD_SCOPE:SELL'))
    OR (
      scope_source = 'condition_pool'
      AND condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'
    )
  ),
  CHECK (allowed_signal_types <@ ARRAY['BUY', 'SELL', 'BUY:FULL', 'SELL:FULL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (scope_source <> 'condition_pool' OR source_condition_pool_id IS NOT NULL),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (previous_day_minute_required = false OR previous_day_minute_date = prev_trade_date),
  CHECK (previous_day_minute_quality_required = false OR previous_day_minute_required = true),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT|.*:BUY$)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT|.*:SELL$)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true))
);

CREATE INDEX idx_board_minute_scope_date
ON board_minute_target_scope(for_trade_date, source_trade_date, direction, scope_status);

CREATE INDEX idx_board_minute_scope_pool
ON board_minute_target_scope(source_condition_pool_id);

COMMIT;
