-- A-share monitor v3 trigger layer schema draft.
-- Stage N4-0 only: review before running in any PostgreSQL database.
-- Boundary: trigger context/state/match/event contract only; no market data
-- pull, no action/user/voice/sim objects, no true trading, and no worker state.
--
-- Depends on:
--   sql/002_condition_layer_schema.sql
--   sql/006_market_data_layer_schema.sql
--   sql/008_common_event_infra_schema.sql

BEGIN;

CREATE TABLE common_trigger_run (
  run_id TEXT PRIMARY KEY,
  source_condition_run_id TEXT NOT NULL REFERENCES common_condition_run(run_id),
  source_market_data_run_id TEXT REFERENCES common_market_data_run(run_id),
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  layer_role TEXT NOT NULL DEFAULT 'N4_trigger' CHECK (layer_role = 'N4_trigger'),
  mode TEXT NOT NULL DEFAULT 'dry_run' CHECK (mode IN ('dry_run', 'preflight', 'execute')),
  status TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'running', 'passed', 'failed', 'blocked', 'superseded', 'rolled_back')),
  p0_count INTEGER NOT NULL DEFAULT 0 CHECK (p0_count >= 0),
  p1_count INTEGER NOT NULL DEFAULT 0 CHECK (p1_count >= 0),
  p2_count INTEGER NOT NULL DEFAULT 0 CHECK (p2_count >= 0),
  source_condition_row_count INTEGER NOT NULL DEFAULT 0 CHECK (source_condition_row_count >= 0),
  context_snapshot_row_count INTEGER NOT NULL DEFAULT 0 CHECK (context_snapshot_row_count >= 0),
  trigger_state_row_count INTEGER NOT NULL DEFAULT 0 CHECK (trigger_state_row_count >= 0),
  trigger_match_row_count INTEGER NOT NULL DEFAULT 0 CHECK (trigger_match_row_count >= 0),
  trigger_event_outbox_count INTEGER NOT NULL DEFAULT 0 CHECK (trigger_event_outbox_count >= 0),
  generated_by TEXT NOT NULL DEFAULT 'trigger_layer',
  market_data_pulled BOOLEAN NOT NULL DEFAULT false,
  action_layer_touched BOOLEAN NOT NULL DEFAULT false,
  user_layer_touched BOOLEAN NOT NULL DEFAULT false,
  voice_touched BOOLEAN NOT NULL DEFAULT false,
  sim_touched BOOLEAN NOT NULL DEFAULT false,
  real_trade_touched BOOLEAN NOT NULL DEFAULT false,
  worker_started BOOLEAN NOT NULL DEFAULT false,
  raw_json JSONB,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (finished_at IS NULL OR finished_at >= started_at),
  CHECK (market_data_pulled = false),
  CHECK (action_layer_touched = false),
  CHECK (user_layer_touched = false),
  CHECK (voice_touched = false),
  CHECK (sim_touched = false),
  CHECK (real_trade_touched = false),
  CHECK (mode <> 'dry_run' OR context_snapshot_row_count = 0),
  CHECK (mode <> 'dry_run' OR trigger_state_row_count = 0),
  CHECK (mode <> 'dry_run' OR trigger_match_row_count = 0),
  CHECK (mode <> 'dry_run' OR trigger_event_outbox_count = 0)
);

CREATE INDEX idx_common_trigger_run_condition
ON common_trigger_run(source_condition_run_id);

CREATE INDEX idx_common_trigger_run_date_status
ON common_trigger_run(for_trade_date, status);

CREATE TABLE common_trigger_quality_item (
  quality_item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_trigger_run(run_id) ON DELETE CASCADE,
  source_condition_run_id TEXT NOT NULL REFERENCES common_condition_run(run_id),
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  data_domain TEXT NOT NULL CHECK (data_domain IN ('common', 'stock', 'index', 'board')),
  layer_scope TEXT NOT NULL CHECK (layer_scope IN ('trigger_context_snapshot', 'trigger_state', 'trigger_match', 'trigger_run', 'event_contract')),
  table_name TEXT,
  gate_code TEXT NOT NULL,
  gate_name TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('P0', 'P1', 'P2')),
  status TEXT NOT NULL CHECK (status IN ('passed', 'failed', 'warning', 'skipped')),
  expected_value TEXT,
  actual_value TEXT,
  identity_key TEXT,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$')
);

CREATE INDEX idx_common_trigger_quality_run
ON common_trigger_quality_item(run_id);

CREATE INDEX idx_common_trigger_quality_status
ON common_trigger_quality_item(severity, status);

CREATE TABLE stock_trigger_context_snapshot (
  trigger_context_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_trigger_run(run_id) ON DELETE CASCADE,
  source_condition_run_id TEXT NOT NULL REFERENCES common_condition_run(run_id),
  source_condition_pool_id BIGINT NOT NULL REFERENCES stock_condition_pool(stock_condition_pool_id),
  source_condition_basis_id BIGINT NOT NULL REFERENCES stock_condition_basis(stock_condition_basis_id),
  source_minute_target_scope_id BIGINT NOT NULL REFERENCES stock_minute_target_scope(stock_minute_target_scope_id),
  source_market_subscription_id BIGINT REFERENCES common_market_data_subscription(subscription_id),
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL DEFAULT 'stock' CHECK (asset_kind = 'stock'),
  identity_key TEXT NOT NULL,
  stock_identity_key TEXT NOT NULL REFERENCES stock_identity(stock_identity_key),
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ')),
  code TEXT NOT NULL,
  display_code TEXT,
  name TEXT NOT NULL,
  lane TEXT NOT NULL CHECK (lane IN ('stock_trade', 'stock_alert')),
  monitor_type TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  amount_y NUMERIC,
  amount_q NUMERIC,
  amount_m NUMERIC,
  amount_w NUMERIC,
  amount_d NUMERIC,
  previous_amount_y NUMERIC,
  previous_amount_q NUMERIC,
  previous_amount_m NUMERIC,
  previous_amount_w NUMERIC,
  previous_amount_d NUMERIC,
  main_up_anchor TEXT CHECK (main_up_anchor IS NULL OR main_up_anchor IN ('Y', 'Q', 'M', 'W')),
  up_reference_period TEXT CHECK (up_reference_period IS NULL OR up_reference_period IN ('Q', 'M', 'W', 'D')),
  up_amplitude NUMERIC,
  buy_target_price NUMERIC,
  main_down_anchor TEXT CHECK (main_down_anchor IS NULL OR main_down_anchor IN ('Y', 'Q', 'M', 'W')),
  down_reference_period TEXT CHECK (down_reference_period IS NULL OR down_reference_period IN ('Q', 'M', 'W', 'D')),
  down_amplitude NUMERIC,
  sell_target_price NUMERIC,
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  previous_day_minute_date TEXT,
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  policy_hash TEXT NOT NULL,
  context_hash TEXT NOT NULL,
  quality_status TEXT NOT NULL DEFAULT 'planned' CHECK (quality_status IN ('planned', 'passed', 'warning', 'failed', 'blocked')),
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, source_minute_target_scope_id),
  UNIQUE(run_id, source_condition_run_id, stock_identity_key, lane, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (identity_key = stock_identity_key),
  CHECK (stock_identity_key = 'stock:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (code !~ '^88[0-9]{4}$'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (allowed_signal_types <@ ARRAY['B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true)),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (context_hash <> '')
);

CREATE INDEX idx_stock_trigger_context_lookup
ON stock_trigger_context_snapshot(run_id, stock_identity_key, direction, condition_key);

CREATE INDEX idx_stock_trigger_context_signal
ON stock_trigger_context_snapshot(run_id, direction, allowed_signal_types);

CREATE TABLE index_trigger_context_snapshot (
  trigger_context_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_trigger_run(run_id) ON DELETE CASCADE,
  source_condition_run_id TEXT NOT NULL REFERENCES common_condition_run(run_id),
  source_condition_pool_id BIGINT NOT NULL REFERENCES index_condition_pool(index_condition_pool_id),
  source_condition_basis_id BIGINT NOT NULL REFERENCES index_condition_basis(index_condition_basis_id),
  source_minute_target_scope_id BIGINT NOT NULL REFERENCES index_minute_target_scope(index_minute_target_scope_id),
  source_market_subscription_id BIGINT REFERENCES common_market_data_subscription(subscription_id),
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL DEFAULT 'index' CHECK (asset_kind = 'index'),
  identity_key TEXT NOT NULL,
  index_identity_key TEXT NOT NULL REFERENCES index_identity(index_identity_key),
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ', 'CSI', 'CNI', 'SW', 'TDX', 'OTH', 'UNKNOWN')),
  code TEXT NOT NULL,
  display_code TEXT,
  name TEXT NOT NULL,
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane = 'market_alert'),
  monitor_type TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  amount_y NUMERIC,
  amount_q NUMERIC,
  amount_m NUMERIC,
  amount_w NUMERIC,
  amount_d NUMERIC,
  previous_amount_y NUMERIC,
  previous_amount_q NUMERIC,
  previous_amount_m NUMERIC,
  previous_amount_w NUMERIC,
  previous_amount_d NUMERIC,
  main_up_anchor TEXT CHECK (main_up_anchor IS NULL OR main_up_anchor IN ('Y', 'Q', 'M', 'W')),
  up_reference_period TEXT CHECK (up_reference_period IS NULL OR up_reference_period IN ('Q', 'M', 'W', 'D')),
  up_amplitude NUMERIC,
  buy_target_price NUMERIC,
  main_down_anchor TEXT CHECK (main_down_anchor IS NULL OR main_down_anchor IN ('Y', 'Q', 'M', 'W')),
  down_reference_period TEXT CHECK (down_reference_period IS NULL OR down_reference_period IN ('Q', 'M', 'W', 'D')),
  down_amplitude NUMERIC,
  sell_target_price NUMERIC,
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  previous_day_minute_date TEXT,
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  policy_hash TEXT NOT NULL,
  context_hash TEXT NOT NULL,
  quality_status TEXT NOT NULL DEFAULT 'planned' CHECK (quality_status IN ('planned', 'passed', 'warning', 'failed', 'blocked')),
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, source_minute_target_scope_id),
  UNIQUE(run_id, source_condition_run_id, index_identity_key, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (identity_key = index_identity_key),
  CHECK (index_identity_key = 'index:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (allowed_signal_types <@ ARRAY['B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true)),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (context_hash <> '')
);

CREATE INDEX idx_index_trigger_context_lookup
ON index_trigger_context_snapshot(run_id, index_identity_key, direction, condition_key);

CREATE INDEX idx_index_trigger_context_signal
ON index_trigger_context_snapshot(run_id, direction, allowed_signal_types);

CREATE TABLE board_trigger_context_snapshot (
  trigger_context_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_trigger_run(run_id) ON DELETE CASCADE,
  source_condition_run_id TEXT NOT NULL REFERENCES common_condition_run(run_id),
  source_condition_pool_id BIGINT NOT NULL REFERENCES board_condition_pool(board_condition_pool_id),
  source_condition_basis_id BIGINT NOT NULL REFERENCES board_condition_basis(board_condition_basis_id),
  source_minute_target_scope_id BIGINT NOT NULL REFERENCES board_minute_target_scope(board_minute_target_scope_id),
  source_market_subscription_id BIGINT REFERENCES common_market_data_subscription(subscription_id),
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL DEFAULT 'board' CHECK (asset_kind = 'board'),
  identity_key TEXT NOT NULL,
  board_identity_key TEXT NOT NULL REFERENCES board_identity(board_identity_key),
  exchange TEXT NOT NULL DEFAULT 'TDX' CHECK (exchange = 'TDX'),
  code TEXT NOT NULL,
  display_code TEXT,
  name TEXT NOT NULL,
  lane TEXT NOT NULL DEFAULT 'market_alert' CHECK (lane = 'market_alert'),
  monitor_type TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  condition_key TEXT NOT NULL,
  condition_periods TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  allowed_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_hint_scope BOOLEAN NOT NULL DEFAULT false,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  amount_y NUMERIC,
  amount_q NUMERIC,
  amount_m NUMERIC,
  amount_w NUMERIC,
  amount_d NUMERIC,
  previous_amount_y NUMERIC,
  previous_amount_q NUMERIC,
  previous_amount_m NUMERIC,
  previous_amount_w NUMERIC,
  previous_amount_d NUMERIC,
  main_up_anchor TEXT CHECK (main_up_anchor IS NULL OR main_up_anchor IN ('Y', 'Q', 'M', 'W')),
  up_reference_period TEXT CHECK (up_reference_period IS NULL OR up_reference_period IN ('Q', 'M', 'W', 'D')),
  up_amplitude NUMERIC,
  buy_target_price NUMERIC,
  main_down_anchor TEXT CHECK (main_down_anchor IS NULL OR main_down_anchor IN ('Y', 'Q', 'M', 'W')),
  down_reference_period TEXT CHECK (down_reference_period IS NULL OR down_reference_period IN ('Q', 'M', 'W', 'D')),
  down_amplitude NUMERIC,
  sell_target_price NUMERIC,
  clear_sell_ref_period TEXT CHECK (clear_sell_ref_period IS NULL OR clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  previous_day_minute_date TEXT,
  daily_snapshot_required BOOLEAN NOT NULL DEFAULT true,
  minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_required BOOLEAN NOT NULL DEFAULT false,
  previous_day_minute_quality_required BOOLEAN NOT NULL DEFAULT false,
  policy_hash TEXT NOT NULL,
  context_hash TEXT NOT NULL,
  quality_status TEXT NOT NULL DEFAULT 'planned' CHECK (quality_status IN ('planned', 'passed', 'warning', 'failed', 'blocked')),
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, source_minute_target_scope_id),
  UNIQUE(run_id, source_condition_run_id, board_identity_key, direction, condition_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (identity_key = board_identity_key),
  CHECK (board_identity_key = 'board:TDX:' || code),
  CHECK (code ~ '^88[0-9]{4}$'),
  CHECK (condition_periods <@ ARRAY['Y', 'Q', 'M', 'W', 'D']::TEXT[]),
  CHECK (allowed_signal_types <@ ARRAY['B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (condition_key ~ '^(BUY:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|SELL:((Y|Q|M|W|D)(,(Y|Q|M|W|D))*|FULL)|BUY_HINT|SELL_HINT)$'),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR (direction = 'buy' AND is_hint_scope = true)),
  CHECK (condition_key <> 'SELL_HINT' OR (direction = 'sell' AND is_hint_scope = true)),
  CHECK (previous_day_minute_date IS NULL OR previous_day_minute_date ~ '^[0-9]{8}$'),
  CHECK (context_hash <> '')
);

CREATE INDEX idx_board_trigger_context_lookup
ON board_trigger_context_snapshot(run_id, board_identity_key, direction, condition_key);

CREATE INDEX idx_board_trigger_context_signal
ON board_trigger_context_snapshot(run_id, direction, allowed_signal_types);

CREATE TABLE common_trigger_state (
  trigger_state_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_trigger_run(run_id) ON DELETE CASCADE,
  source_condition_run_id TEXT NOT NULL REFERENCES common_condition_run(run_id),
  for_trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL CHECK (asset_kind IN ('stock', 'index', 'board')),
  identity_key TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  signal_type TEXT NOT NULL CHECK (signal_type IN ('B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT')),
  condition_key TEXT NOT NULL,
  trigger_period TEXT NOT NULL CHECK (trigger_period IN ('Y', 'Q', 'M', 'W', 'D', '30m')),
  trigger_bucket TEXT NOT NULL,
  current_status TEXT NOT NULL DEFAULT 'inactive' CHECK (current_status IN ('inactive', 'pending_market_data', 'matched', 'cleared')),
  last_source_event_id TEXT,
  last_trigger_match_id BIGINT,
  data_quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (data_quality_status IN ('pending', 'passed', 'partial', 'missing', 'delayed', 'failed')),
  context_hash TEXT,
  match_count INTEGER NOT NULL DEFAULT 0 CHECK (match_count >= 0),
  first_matched_at TIMESTAMPTZ,
  last_matched_at TIMESTAMPTZ,
  cleared_at TIMESTAMPTZ,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, for_trade_date, asset_kind, identity_key, direction, signal_type, condition_key, trigger_period, trigger_bucket),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (identity_key LIKE asset_kind || ':%'),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (signal_type NOT IN ('B_BUY_30M_VOL', 'B_BUY', 'BUY_HINT') OR direction = 'buy'),
  CHECK (signal_type NOT IN ('S_SELL_30M_SHRINK', 'S_SELL', 'SELL_HINT') OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR signal_type = 'BUY_HINT'),
  CHECK (condition_key <> 'SELL_HINT' OR signal_type = 'SELL_HINT'),
  CHECK (trigger_bucket <> '')
);

CREATE INDEX idx_common_trigger_state_lookup
ON common_trigger_state(run_id, asset_kind, identity_key, current_status);

CREATE INDEX idx_common_trigger_state_event
ON common_trigger_state(last_source_event_id);

CREATE TABLE common_trigger_match (
  trigger_match_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_trigger_run(run_id) ON DELETE CASCADE,
  trigger_state_id BIGINT NOT NULL REFERENCES common_trigger_state(trigger_state_id) ON DELETE CASCADE,
  source_event_id TEXT NOT NULL,
  source_event_type TEXT NOT NULL CHECK (source_event_type IN ('MarketSnapshotUpdated', 'MinuteBarClosed', 'MarketDataDelayed', 'MarketDataMissing')),
  source_condition_run_id TEXT NOT NULL REFERENCES common_condition_run(run_id),
  source_condition_pool_id BIGINT,
  source_condition_basis_id BIGINT,
  source_market_subscription_id BIGINT REFERENCES common_market_data_subscription(subscription_id),
  for_trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL CHECK (asset_kind IN ('stock', 'index', 'board')),
  identity_key TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('buy', 'sell')),
  signal_type TEXT NOT NULL CHECK (signal_type IN ('B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT')),
  condition_key TEXT NOT NULL,
  trigger_price NUMERIC,
  trigger_time TIMESTAMPTZ NOT NULL,
  trigger_period TEXT NOT NULL CHECK (trigger_period IN ('Y', 'Q', 'M', 'W', 'D', '30m')),
  trigger_bucket TEXT NOT NULL,
  data_quality_status TEXT NOT NULL CHECK (data_quality_status IN ('passed', 'partial', 'missing', 'delayed', 'failed')),
  output_event_type TEXT NOT NULL CHECK (output_event_type IN ('TriggerMatched', 'TriggerCleared', 'TriggerPendingMarketData')),
  output_event_id TEXT NOT NULL,
  dedup_key TEXT NOT NULL,
  context_hash TEXT,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, source_event_id, asset_kind, identity_key, direction, signal_type, condition_key, trigger_period, trigger_bucket),
  UNIQUE(output_event_id),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (identity_key LIKE asset_kind || ':%'),
  CHECK (condition_key !~ '^(BUY:|BUY_HINT)' OR direction = 'buy'),
  CHECK (condition_key !~ '^(SELL:|SELL_HINT)' OR direction = 'sell'),
  CHECK (signal_type NOT IN ('B_BUY_30M_VOL', 'B_BUY', 'BUY_HINT') OR direction = 'buy'),
  CHECK (signal_type NOT IN ('S_SELL_30M_SHRINK', 'S_SELL', 'SELL_HINT') OR direction = 'sell'),
  CHECK (condition_key <> 'BUY_HINT' OR signal_type = 'BUY_HINT'),
  CHECK (condition_key <> 'SELL_HINT' OR signal_type = 'SELL_HINT'),
  CHECK (source_event_id <> ''),
  CHECK (output_event_id <> ''),
  CHECK (dedup_key <> ''),
  CHECK (trigger_bucket <> '')
);

CREATE INDEX idx_common_trigger_match_run
ON common_trigger_match(run_id, output_event_type, created_at);

CREATE INDEX idx_common_trigger_match_identity
ON common_trigger_match(for_trade_date, asset_kind, identity_key, trigger_time DESC);

COMMIT;
