-- N2-Display-1 additive migration draft: condition display basis tables.
-- Do not execute without explicit user confirmation.
-- Scope: create N2 display-input tables only.
-- Boundary: no N3/N4/N5 contract change, no trigger/action/user runtime fields.

BEGIN;

CREATE TABLE IF NOT EXISTS stock_condition_display_basis (
  stock_condition_display_basis_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  stock_identity_key TEXT NOT NULL REFERENCES stock_identity(stock_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ')),
  name TEXT NOT NULL,
  display_code TEXT,
  display_name TEXT,
  display_title TEXT,
  display_summary TEXT,
  selected_directions TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_condition_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_lanes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_monitor_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  condition_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  target_price_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  reference_period_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_grade_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_transition_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_grade_y TEXT,
  period_grade_q TEXT,
  period_grade_m TEXT,
  period_grade_w TEXT,
  period_grade_d TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  buy_target_price NUMERIC,
  buy_expected_return_pct NUMERIC,
  sell_target_price NUMERIC,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT NOT NULL DEFAULT 'D' CHECK (clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  period_trigger_baseline_json JSONB,
  total_mv NUMERIC,
  circ_mv NUMERIC,
  pe_core NUMERIC,
  score NUMERIC,
  recommendation_level TEXT,
  recommendation_reason TEXT,
  is_st BOOLEAN NOT NULL DEFAULT false,
  stock_status TEXT NOT NULL DEFAULT 'unknown' CHECK (stock_status IN ('active', 'delisted', 'paused', 'unknown')),
  official_daily_proof BOOLEAN NOT NULL DEFAULT false,
  financial_quality_status TEXT,
  cash_realization_rate NUMERIC,
  revenue_yoy_pct NUMERIC,
  core_profit_yoy_pct NUMERIC,
  report_core_revenue NUMERIC,
  report_core_profit NUMERIC,
  core_profit_ttm NUMERIC,
  core_gt_revenue_yoy BOOLEAN,
  revenue_growth_streak_q INTEGER,
  core_growth_streak_q INTEGER,
  core_gt_revenue_streak_q INTEGER,
  forecast_type TEXT,
  forecast_score NUMERIC,
  score_breakdown_json JSONB,
  financial_warning_json JSONB,
  financial_metric_version TEXT,
  main_index_identity_key TEXT REFERENCES index_identity(index_identity_key),
  main_index_code TEXT,
  main_index_name TEXT,
  preferred_board_identity_key TEXT REFERENCES board_identity(board_identity_key),
  preferred_board_code TEXT,
  preferred_board_name TEXT,
  linked_board_identity_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  display_policy_name TEXT NOT NULL DEFAULT 'default_condition_display_policy',
  display_policy_hash TEXT NOT NULL,
  condition_pool_policy_name TEXT,
  condition_pool_policy_hash TEXT,
  scope_policy_name TEXT,
  scope_policy_hash TEXT,
  display_scope_reason TEXT,
  selected_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  excluded_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  primary_source_condition_basis_id BIGINT NOT NULL REFERENCES stock_condition_basis(stock_condition_basis_id),
  primary_source_condition_pool_id BIGINT REFERENCES stock_condition_pool(stock_condition_pool_id),
  primary_source_minute_target_scope_id BIGINT REFERENCES stock_minute_target_scope(stock_minute_target_scope_id),
  source_condition_basis_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_condition_pool_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_minute_target_scope_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_row_count_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  source_version TEXT NOT NULL,
  display_status TEXT NOT NULL DEFAULT 'visible' CHECK (display_status IN ('visible', 'hidden', 'skipped', 'blocked')),
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, stock_identity_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (stock_identity_key = 'stock:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (code !~ '^88[0-9]{4}$'),
  CHECK (selected_directions <@ ARRAY['buy', 'sell']::TEXT[]),
  CHECK (selected_signal_types <@ ARRAY['B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (selected_lanes <@ ARRAY['stock_trade', 'stock_alert']::TEXT[]),
  CHECK (clear_sell_ref_period = up_sell_reference_period),
  CHECK (jsonb_typeof(condition_summary_json) = 'object'),
  CHECK (jsonb_typeof(target_price_summary_json) = 'object'),
  CHECK (jsonb_typeof(reference_period_summary_json) = 'object'),
  CHECK (jsonb_typeof(period_grade_summary_json) = 'object'),
  CHECK (jsonb_typeof(period_transition_summary_json) = 'object'),
  CHECK (jsonb_typeof(source_condition_basis_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_condition_pool_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_minute_target_scope_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_row_count_json) = 'object'),
  CHECK (period_grade_y IS NULL OR period_grade_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_q IS NULL OR period_grade_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_m IS NULL OR period_grade_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_w IS NULL OR period_grade_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_d IS NULL OR period_grade_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_y IS NULL OR period_transition_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_q IS NULL OR period_transition_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_m IS NULL OR period_transition_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_w IS NULL OR period_transition_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_d IS NULL OR period_transition_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown'))
);

CREATE INDEX IF NOT EXISTS idx_stock_condition_display_basis_run
ON stock_condition_display_basis(run_id);

CREATE INDEX IF NOT EXISTS idx_stock_condition_display_basis_date_status
ON stock_condition_display_basis(for_trade_date, source_trade_date, display_status, quality_status);

CREATE INDEX IF NOT EXISTS idx_stock_condition_display_basis_identity
ON stock_condition_display_basis(stock_identity_key, for_trade_date);

CREATE INDEX IF NOT EXISTS idx_stock_condition_display_basis_policy
ON stock_condition_display_basis(display_policy_hash);

CREATE INDEX IF NOT EXISTS idx_stock_condition_display_basis_total_mv
ON stock_condition_display_basis(for_trade_date, total_mv);

CREATE TABLE IF NOT EXISTS index_condition_display_basis (
  index_condition_display_basis_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  index_identity_key TEXT NOT NULL REFERENCES index_identity(index_identity_key),
  code TEXT NOT NULL,
  exchange TEXT NOT NULL CHECK (exchange IN ('SH', 'SZ', 'BJ', 'CSI', 'CNI', 'SW', 'TDX', 'OTH', 'UNKNOWN')),
  name TEXT NOT NULL,
  display_code TEXT,
  display_name TEXT,
  display_title TEXT,
  display_summary TEXT,
  fixed_index_member BOOLEAN NOT NULL DEFAULT false,
  selected_directions TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_condition_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_lanes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_monitor_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  condition_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  target_price_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  reference_period_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_grade_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_transition_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_grade_y TEXT,
  period_grade_q TEXT,
  period_grade_m TEXT,
  period_grade_w TEXT,
  period_grade_d TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  buy_target_price NUMERIC,
  buy_expected_return_pct NUMERIC,
  sell_target_price NUMERIC,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT NOT NULL DEFAULT 'D' CHECK (clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  period_trigger_baseline_json JSONB,
  display_policy_name TEXT NOT NULL DEFAULT 'default_condition_display_policy',
  display_policy_hash TEXT NOT NULL,
  condition_pool_policy_name TEXT,
  condition_pool_policy_hash TEXT,
  scope_policy_name TEXT,
  scope_policy_hash TEXT,
  display_scope_reason TEXT,
  selected_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  excluded_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  primary_source_condition_basis_id BIGINT NOT NULL REFERENCES index_condition_basis(index_condition_basis_id),
  primary_source_condition_pool_id BIGINT REFERENCES index_condition_pool(index_condition_pool_id),
  primary_source_minute_target_scope_id BIGINT REFERENCES index_minute_target_scope(index_minute_target_scope_id),
  source_condition_basis_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_condition_pool_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_minute_target_scope_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_row_count_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  source_version TEXT NOT NULL,
  display_status TEXT NOT NULL DEFAULT 'visible' CHECK (display_status IN ('visible', 'hidden', 'skipped', 'blocked')),
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, index_identity_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (index_identity_key = 'index:' || exchange || ':' || code),
  CHECK (code ~ '^[0-9]{6}$'),
  CHECK (selected_directions <@ ARRAY['buy', 'sell']::TEXT[]),
  CHECK (selected_signal_types <@ ARRAY['B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (selected_lanes <@ ARRAY['market_alert']::TEXT[]),
  CHECK (clear_sell_ref_period = up_sell_reference_period),
  CHECK (jsonb_typeof(condition_summary_json) = 'object'),
  CHECK (jsonb_typeof(target_price_summary_json) = 'object'),
  CHECK (jsonb_typeof(reference_period_summary_json) = 'object'),
  CHECK (jsonb_typeof(period_grade_summary_json) = 'object'),
  CHECK (jsonb_typeof(period_transition_summary_json) = 'object'),
  CHECK (jsonb_typeof(source_condition_basis_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_condition_pool_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_minute_target_scope_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_row_count_json) = 'object'),
  CHECK (period_grade_y IS NULL OR period_grade_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_q IS NULL OR period_grade_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_m IS NULL OR period_grade_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_w IS NULL OR period_grade_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_d IS NULL OR period_grade_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_y IS NULL OR period_transition_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_q IS NULL OR period_transition_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_m IS NULL OR period_transition_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_w IS NULL OR period_transition_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_d IS NULL OR period_transition_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown'))
);

CREATE INDEX IF NOT EXISTS idx_index_condition_display_basis_run
ON index_condition_display_basis(run_id);

CREATE INDEX IF NOT EXISTS idx_index_condition_display_basis_date_status
ON index_condition_display_basis(for_trade_date, source_trade_date, display_status, quality_status);

CREATE INDEX IF NOT EXISTS idx_index_condition_display_basis_identity
ON index_condition_display_basis(index_identity_key, for_trade_date);

CREATE INDEX IF NOT EXISTS idx_index_condition_display_basis_policy
ON index_condition_display_basis(display_policy_hash);

CREATE TABLE IF NOT EXISTS board_condition_display_basis (
  board_condition_display_basis_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES common_condition_run(run_id) ON DELETE CASCADE,
  for_trade_date TEXT NOT NULL,
  source_trade_date TEXT NOT NULL,
  prev_trade_date TEXT NOT NULL,
  board_identity_key TEXT NOT NULL REFERENCES board_identity(board_identity_key),
  board_code TEXT NOT NULL,
  board_name TEXT NOT NULL,
  board_type TEXT NOT NULL CHECK (board_type IN ('tdx_region', 'tdx_concept', 'tdx_industry', 'tdx_other')),
  display_code TEXT,
  display_name TEXT,
  display_title TEXT,
  display_summary TEXT,
  is_industry_board BOOLEAN NOT NULL DEFAULT false,
  selected_directions TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_condition_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_signal_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_lanes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  selected_monitor_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  condition_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  target_price_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  reference_period_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_grade_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_transition_summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  period_grade_y TEXT,
  period_grade_q TEXT,
  period_grade_m TEXT,
  period_grade_w TEXT,
  period_grade_d TEXT,
  period_transition_y TEXT,
  period_transition_q TEXT,
  period_transition_m TEXT,
  period_transition_w TEXT,
  period_transition_d TEXT,
  prev_up_str TEXT,
  prev_dn_str TEXT,
  buy_target_price NUMERIC,
  buy_expected_return_pct NUMERIC,
  sell_target_price NUMERIC,
  up_sell_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (up_sell_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  down_buy_reference_period TEXT NOT NULL DEFAULT 'D' CHECK (down_buy_reference_period IN ('Y', 'Q', 'M', 'W', 'D')),
  clear_sell_ref_period TEXT NOT NULL DEFAULT 'D' CHECK (clear_sell_ref_period IN ('Y', 'Q', 'M', 'W', 'D')),
  period_trigger_baseline_json JSONB,
  display_policy_name TEXT NOT NULL DEFAULT 'default_condition_display_policy',
  display_policy_hash TEXT NOT NULL,
  condition_pool_policy_name TEXT,
  condition_pool_policy_hash TEXT,
  scope_policy_name TEXT,
  scope_policy_hash TEXT,
  display_scope_reason TEXT,
  selected_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  excluded_reason TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  primary_source_condition_basis_id BIGINT NOT NULL REFERENCES board_condition_basis(board_condition_basis_id),
  primary_source_condition_pool_id BIGINT REFERENCES board_condition_pool(board_condition_pool_id),
  primary_source_minute_target_scope_id BIGINT REFERENCES board_minute_target_scope(board_minute_target_scope_id),
  source_condition_basis_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_condition_pool_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_minute_target_scope_ids_json JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_row_count_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  source_version TEXT NOT NULL,
  display_status TEXT NOT NULL DEFAULT 'visible' CHECK (display_status IN ('visible', 'hidden', 'skipped', 'blocked')),
  quality_status TEXT NOT NULL DEFAULT 'pending' CHECK (quality_status IN ('pending', 'passed', 'warning', 'failed', 'blocked')),
  quality_reason TEXT,
  missing_fields_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, board_identity_key),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date ~ '^[0-9]{8}$'),
  CHECK (prev_trade_date ~ '^[0-9]{8}$'),
  CHECK (source_trade_date = prev_trade_date),
  CHECK (board_identity_key = 'board:TDX:' || board_code),
  CHECK (board_code ~ '^88[0-9]{4}$'),
  CHECK (selected_directions <@ ARRAY['buy', 'sell']::TEXT[]),
  CHECK (selected_signal_types <@ ARRAY['B_BUY_30M_VOL', 'B_BUY', 'S_SELL_30M_SHRINK', 'S_SELL', 'BUY_HINT', 'SELL_HINT']::TEXT[]),
  CHECK (selected_lanes <@ ARRAY['market_alert']::TEXT[]),
  CHECK (clear_sell_ref_period = up_sell_reference_period),
  CHECK (jsonb_typeof(condition_summary_json) = 'object'),
  CHECK (jsonb_typeof(target_price_summary_json) = 'object'),
  CHECK (jsonb_typeof(reference_period_summary_json) = 'object'),
  CHECK (jsonb_typeof(period_grade_summary_json) = 'object'),
  CHECK (jsonb_typeof(period_transition_summary_json) = 'object'),
  CHECK (jsonb_typeof(source_condition_basis_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_condition_pool_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_minute_target_scope_ids_json) = 'array'),
  CHECK (jsonb_typeof(source_row_count_json) = 'object'),
  CHECK (period_grade_y IS NULL OR period_grade_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_q IS NULL OR period_grade_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_m IS NULL OR period_grade_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_w IS NULL OR period_grade_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_grade_d IS NULL OR period_grade_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_y IS NULL OR period_transition_y IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_q IS NULL OR period_transition_q IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_m IS NULL OR period_transition_m IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_w IS NULL OR period_transition_w IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown')),
  CHECK (period_transition_d IS NULL OR period_transition_d IN ('volume_up', 'low_volume_up', 'volume_down', 'low_volume_down', 'flat', 'unknown'))
);

CREATE INDEX IF NOT EXISTS idx_board_condition_display_basis_run
ON board_condition_display_basis(run_id);

CREATE INDEX IF NOT EXISTS idx_board_condition_display_basis_date_status
ON board_condition_display_basis(for_trade_date, source_trade_date, display_status, quality_status);

CREATE INDEX IF NOT EXISTS idx_board_condition_display_basis_identity
ON board_condition_display_basis(board_identity_key, for_trade_date);

CREATE INDEX IF NOT EXISTS idx_board_condition_display_basis_policy
ON board_condition_display_basis(display_policy_hash);

COMMIT;
