-- A-share monitor v3 realtime virtual metric schema rollback draft.
-- Draft only. Do not execute without a separate runtime-control final gate.

DO $$
BEGIN
  RAISE EXCEPTION 'v3 realtime virtual metric schema rollback blocked by default; remove only after scoped final gate approval';
END $$;

DO $$
DECLARE
  downstream_refs INTEGER := 0;
BEGIN
  SELECT COUNT(*) INTO downstream_refs
  FROM common_trigger_state
  WHERE raw_json::TEXT LIKE '%v3.realtime_virtual_metric.v1%';

  IF downstream_refs <> 0 THEN
    RAISE EXCEPTION 'v3 realtime virtual metric schema rollback blocked: downstream_refs=%', downstream_refs;
  END IF;
END $$;

ALTER TABLE stock_action_confirmation_projection_metric
  DROP COLUMN IF EXISTS realtime_metric_schema_version,
  DROP COLUMN IF EXISTS metric_time_label,
  DROP COLUMN IF EXISTS source_time,
  DROP COLUMN IF EXISTS observed_at,
  DROP COLUMN IF EXISTS snapshot_id,
  DROP COLUMN IF EXISTS event_id,
  DROP COLUMN IF EXISTS quality_status,
  DROP COLUMN IF EXISTS session_kind,
  DROP COLUMN IF EXISTS period_source,
  DROP COLUMN IF EXISTS is_closed_1m,
  DROP COLUMN IF EXISTS is_auction_virtual,
  DROP COLUMN IF EXISTS midday_bridge_policy,
  DROP COLUMN IF EXISTS deterministic_pass_flags,
  DROP COLUMN IF EXISTS current_1m_body_high,
  DROP COLUMN IF EXISTS current_1m_body_low,
  DROP COLUMN IF EXISTS current_5m_body_high,
  DROP COLUMN IF EXISTS current_5m_body_low,
  DROP COLUMN IF EXISTS current_30m_body_high,
  DROP COLUMN IF EXISTS current_30m_body_low,
  DROP COLUMN IF EXISTS current_120m_body_high,
  DROP COLUMN IF EXISTS current_120m_body_low,
  DROP COLUMN IF EXISTS current_d_body_high,
  DROP COLUMN IF EXISTS current_d_body_low,
  DROP COLUMN IF EXISTS current_w_body_high,
  DROP COLUMN IF EXISTS current_w_body_low,
  DROP COLUMN IF EXISTS current_m_body_high,
  DROP COLUMN IF EXISTS current_m_body_low,
  DROP COLUMN IF EXISTS current_q_body_high,
  DROP COLUMN IF EXISTS current_q_body_low,
  DROP COLUMN IF EXISTS current_y_body_high,
  DROP COLUMN IF EXISTS current_y_body_low,
  DROP COLUMN IF EXISTS previous_d_body_high,
  DROP COLUMN IF EXISTS previous_d_body_low,
  DROP COLUMN IF EXISTS previous_w_body_high,
  DROP COLUMN IF EXISTS previous_w_body_low,
  DROP COLUMN IF EXISTS previous_m_body_high,
  DROP COLUMN IF EXISTS previous_m_body_low,
  DROP COLUMN IF EXISTS previous_q_body_high,
  DROP COLUMN IF EXISTS previous_q_body_low,
  DROP COLUMN IF EXISTS previous_y_body_high,
  DROP COLUMN IF EXISTS previous_y_body_low,
  DROP COLUMN IF EXISTS current_30m_virtual_amount,
  DROP COLUMN IF EXISTS previous_day_same_window_amount,
  DROP COLUMN IF EXISTS previous_30m_full_amount,
  DROP COLUMN IF EXISTS current_120m_virtual_amount,
  DROP COLUMN IF EXISTS previous_120m_full_amount,
  DROP COLUMN IF EXISTS current_d_virtual_amount,
  DROP COLUMN IF EXISTS previous_d_amount,
  DROP COLUMN IF EXISTS current_w_virtual_amount,
  DROP COLUMN IF EXISTS previous_w_amount,
  DROP COLUMN IF EXISTS current_m_virtual_amount,
  DROP COLUMN IF EXISTS previous_m_amount,
  DROP COLUMN IF EXISTS current_q_virtual_amount,
  DROP COLUMN IF EXISTS previous_q_amount,
  DROP COLUMN IF EXISTS current_y_virtual_amount,
  DROP COLUMN IF EXISTS previous_y_amount,
  DROP COLUMN IF EXISTS trace_json;

ALTER TABLE index_action_confirmation_projection_metric
  DROP COLUMN IF EXISTS realtime_metric_schema_version,
  DROP COLUMN IF EXISTS metric_time_label,
  DROP COLUMN IF EXISTS source_time,
  DROP COLUMN IF EXISTS observed_at,
  DROP COLUMN IF EXISTS snapshot_id,
  DROP COLUMN IF EXISTS event_id,
  DROP COLUMN IF EXISTS quality_status,
  DROP COLUMN IF EXISTS session_kind,
  DROP COLUMN IF EXISTS period_source,
  DROP COLUMN IF EXISTS is_closed_1m,
  DROP COLUMN IF EXISTS is_auction_virtual,
  DROP COLUMN IF EXISTS midday_bridge_policy,
  DROP COLUMN IF EXISTS deterministic_pass_flags,
  DROP COLUMN IF EXISTS current_1m_body_high,
  DROP COLUMN IF EXISTS current_1m_body_low,
  DROP COLUMN IF EXISTS current_5m_body_high,
  DROP COLUMN IF EXISTS current_5m_body_low,
  DROP COLUMN IF EXISTS current_30m_body_high,
  DROP COLUMN IF EXISTS current_30m_body_low,
  DROP COLUMN IF EXISTS current_120m_body_high,
  DROP COLUMN IF EXISTS current_120m_body_low,
  DROP COLUMN IF EXISTS current_d_body_high,
  DROP COLUMN IF EXISTS current_d_body_low,
  DROP COLUMN IF EXISTS current_w_body_high,
  DROP COLUMN IF EXISTS current_w_body_low,
  DROP COLUMN IF EXISTS current_m_body_high,
  DROP COLUMN IF EXISTS current_m_body_low,
  DROP COLUMN IF EXISTS current_q_body_high,
  DROP COLUMN IF EXISTS current_q_body_low,
  DROP COLUMN IF EXISTS current_y_body_high,
  DROP COLUMN IF EXISTS current_y_body_low,
  DROP COLUMN IF EXISTS previous_d_body_high,
  DROP COLUMN IF EXISTS previous_d_body_low,
  DROP COLUMN IF EXISTS previous_w_body_high,
  DROP COLUMN IF EXISTS previous_w_body_low,
  DROP COLUMN IF EXISTS previous_m_body_high,
  DROP COLUMN IF EXISTS previous_m_body_low,
  DROP COLUMN IF EXISTS previous_q_body_high,
  DROP COLUMN IF EXISTS previous_q_body_low,
  DROP COLUMN IF EXISTS previous_y_body_high,
  DROP COLUMN IF EXISTS previous_y_body_low,
  DROP COLUMN IF EXISTS current_30m_virtual_amount,
  DROP COLUMN IF EXISTS previous_day_same_window_amount,
  DROP COLUMN IF EXISTS previous_30m_full_amount,
  DROP COLUMN IF EXISTS current_120m_virtual_amount,
  DROP COLUMN IF EXISTS previous_120m_full_amount,
  DROP COLUMN IF EXISTS current_d_virtual_amount,
  DROP COLUMN IF EXISTS previous_d_amount,
  DROP COLUMN IF EXISTS current_w_virtual_amount,
  DROP COLUMN IF EXISTS previous_w_amount,
  DROP COLUMN IF EXISTS current_m_virtual_amount,
  DROP COLUMN IF EXISTS previous_m_amount,
  DROP COLUMN IF EXISTS current_q_virtual_amount,
  DROP COLUMN IF EXISTS previous_q_amount,
  DROP COLUMN IF EXISTS current_y_virtual_amount,
  DROP COLUMN IF EXISTS previous_y_amount,
  DROP COLUMN IF EXISTS trace_json;

ALTER TABLE board_action_confirmation_projection_metric
  DROP COLUMN IF EXISTS realtime_metric_schema_version,
  DROP COLUMN IF EXISTS metric_time_label,
  DROP COLUMN IF EXISTS source_time,
  DROP COLUMN IF EXISTS observed_at,
  DROP COLUMN IF EXISTS snapshot_id,
  DROP COLUMN IF EXISTS event_id,
  DROP COLUMN IF EXISTS quality_status,
  DROP COLUMN IF EXISTS session_kind,
  DROP COLUMN IF EXISTS period_source,
  DROP COLUMN IF EXISTS is_closed_1m,
  DROP COLUMN IF EXISTS is_auction_virtual,
  DROP COLUMN IF EXISTS midday_bridge_policy,
  DROP COLUMN IF EXISTS deterministic_pass_flags,
  DROP COLUMN IF EXISTS current_1m_body_high,
  DROP COLUMN IF EXISTS current_1m_body_low,
  DROP COLUMN IF EXISTS current_5m_body_high,
  DROP COLUMN IF EXISTS current_5m_body_low,
  DROP COLUMN IF EXISTS current_30m_body_high,
  DROP COLUMN IF EXISTS current_30m_body_low,
  DROP COLUMN IF EXISTS current_120m_body_high,
  DROP COLUMN IF EXISTS current_120m_body_low,
  DROP COLUMN IF EXISTS current_d_body_high,
  DROP COLUMN IF EXISTS current_d_body_low,
  DROP COLUMN IF EXISTS current_w_body_high,
  DROP COLUMN IF EXISTS current_w_body_low,
  DROP COLUMN IF EXISTS current_m_body_high,
  DROP COLUMN IF EXISTS current_m_body_low,
  DROP COLUMN IF EXISTS current_q_body_high,
  DROP COLUMN IF EXISTS current_q_body_low,
  DROP COLUMN IF EXISTS current_y_body_high,
  DROP COLUMN IF EXISTS current_y_body_low,
  DROP COLUMN IF EXISTS previous_d_body_high,
  DROP COLUMN IF EXISTS previous_d_body_low,
  DROP COLUMN IF EXISTS previous_w_body_high,
  DROP COLUMN IF EXISTS previous_w_body_low,
  DROP COLUMN IF EXISTS previous_m_body_high,
  DROP COLUMN IF EXISTS previous_m_body_low,
  DROP COLUMN IF EXISTS previous_q_body_high,
  DROP COLUMN IF EXISTS previous_q_body_low,
  DROP COLUMN IF EXISTS previous_y_body_high,
  DROP COLUMN IF EXISTS previous_y_body_low,
  DROP COLUMN IF EXISTS current_30m_virtual_amount,
  DROP COLUMN IF EXISTS previous_day_same_window_amount,
  DROP COLUMN IF EXISTS previous_30m_full_amount,
  DROP COLUMN IF EXISTS current_120m_virtual_amount,
  DROP COLUMN IF EXISTS previous_120m_full_amount,
  DROP COLUMN IF EXISTS current_d_virtual_amount,
  DROP COLUMN IF EXISTS previous_d_amount,
  DROP COLUMN IF EXISTS current_w_virtual_amount,
  DROP COLUMN IF EXISTS previous_w_amount,
  DROP COLUMN IF EXISTS current_m_virtual_amount,
  DROP COLUMN IF EXISTS previous_m_amount,
  DROP COLUMN IF EXISTS current_q_virtual_amount,
  DROP COLUMN IF EXISTS previous_q_amount,
  DROP COLUMN IF EXISTS current_y_virtual_amount,
  DROP COLUMN IF EXISTS previous_y_amount,
  DROP COLUMN IF EXISTS trace_json;
