-- A-share monitor v3 realtime virtual metric additive schema draft.
-- Stage: V3 realtime signal/action engine N3 metric contract.
-- Draft only. Do not execute without a separate migration final gate.
-- No business rows, no event ledger writes, no N4/N5/N6 writes, no worker,
-- and no real trading.

ALTER TABLE stock_action_confirmation_projection_metric
  ADD COLUMN IF NOT EXISTS realtime_metric_schema_version TEXT NOT NULL DEFAULT 'v3.realtime_virtual_metric.v1',
  ADD COLUMN IF NOT EXISTS metric_time_label TEXT,
  ADD COLUMN IF NOT EXISTS source_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS observed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS snapshot_id BIGINT,
  ADD COLUMN IF NOT EXISTS event_id TEXT,
  ADD COLUMN IF NOT EXISTS quality_status TEXT,
  ADD COLUMN IF NOT EXISTS session_kind TEXT NOT NULL DEFAULT 'regular',
  ADD COLUMN IF NOT EXISTS period_source JSONB NOT NULL DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS is_closed_1m BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_auction_virtual BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS midday_bridge_policy TEXT,
  ADD COLUMN IF NOT EXISTS deterministic_pass_flags JSONB NOT NULL DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS current_1m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_1m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_5m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_5m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_day_same_window_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_30m_full_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_120m_full_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS trace_json JSONB NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE index_action_confirmation_projection_metric
  ADD COLUMN IF NOT EXISTS realtime_metric_schema_version TEXT NOT NULL DEFAULT 'v3.realtime_virtual_metric.v1',
  ADD COLUMN IF NOT EXISTS metric_time_label TEXT,
  ADD COLUMN IF NOT EXISTS source_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS observed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS snapshot_id BIGINT,
  ADD COLUMN IF NOT EXISTS event_id TEXT,
  ADD COLUMN IF NOT EXISTS quality_status TEXT,
  ADD COLUMN IF NOT EXISTS session_kind TEXT NOT NULL DEFAULT 'regular',
  ADD COLUMN IF NOT EXISTS period_source JSONB NOT NULL DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS is_closed_1m BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_auction_virtual BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS midday_bridge_policy TEXT,
  ADD COLUMN IF NOT EXISTS deterministic_pass_flags JSONB NOT NULL DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS current_1m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_1m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_5m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_5m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_day_same_window_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_30m_full_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_120m_full_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS trace_json JSONB NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE board_action_confirmation_projection_metric
  ADD COLUMN IF NOT EXISTS realtime_metric_schema_version TEXT NOT NULL DEFAULT 'v3.realtime_virtual_metric.v1',
  ADD COLUMN IF NOT EXISTS metric_time_label TEXT,
  ADD COLUMN IF NOT EXISTS source_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS observed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS snapshot_id BIGINT,
  ADD COLUMN IF NOT EXISTS event_id TEXT,
  ADD COLUMN IF NOT EXISTS quality_status TEXT,
  ADD COLUMN IF NOT EXISTS session_kind TEXT NOT NULL DEFAULT 'regular',
  ADD COLUMN IF NOT EXISTS period_source JSONB NOT NULL DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS is_closed_1m BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_auction_virtual BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS midday_bridge_policy TEXT,
  ADD COLUMN IF NOT EXISTS deterministic_pass_flags JSONB NOT NULL DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS current_1m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_1m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_5m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_5m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_body_high NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_body_low NUMERIC,
  ADD COLUMN IF NOT EXISTS current_30m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_day_same_window_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_30m_full_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_120m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_120m_full_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_d_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_d_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_w_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_w_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_m_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_m_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_q_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_q_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS current_y_virtual_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS previous_y_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS trace_json JSONB NOT NULL DEFAULT '{}'::JSONB;

CREATE INDEX IF NOT EXISTS idx_stock_action_confirmation_metric_realtime_session
ON stock_action_confirmation_projection_metric(trade_date, metric_minute_label, session_kind, metric_ready);

CREATE INDEX IF NOT EXISTS idx_index_action_confirmation_metric_realtime_session
ON index_action_confirmation_projection_metric(trade_date, metric_minute_label, session_kind, metric_ready);

CREATE INDEX IF NOT EXISTS idx_board_action_confirmation_metric_realtime_session
ON board_action_confirmation_projection_metric(trade_date, metric_minute_label, session_kind, metric_ready);
