-- N1 daily catch-up 20260603 rollback.
-- Scope: official daily + condition source batches generated by
-- scripts/run_real_daily_incremental.py --trade-date 20260603 --version v1
-- excluding trade_calendar, which is managed by its own calendar patch SQL.

BEGIN;

DO $$
DECLARE
  v_trade_date text := '20260603';
  v_versions text[] := ARRAY[
    'stock_identity_20260603_v1',
    'index_identity_20260603_v1',
    'board_identity_20260603_v1',
    'stock_daily_20260603_v1',
    'index_daily_20260603_v1',
    'board_daily_20260603_v1',
    'stock_daily_basic_20260603_v1',
    'stock_financial_20260603_v1',
    'index_membership_20260603_v1',
    'board_membership_20260603_v1'
  ];
  v_outbox_refs bigint;
  v_inbox_refs bigint;
  v_checkpoint_refs bigint;
  v_n2_refs bigint;
  v_n3_refs bigint;
  v_n4_refs bigint;
  v_n5_refs bigint;
  v_n6_refs bigint;
BEGIN
  SELECT COUNT(*)
  INTO v_outbox_refs
  FROM common_event_outbox
  WHERE source_run_id = ANY(v_versions)
     OR EXISTS (
       SELECT 1 FROM unnest(v_versions) AS v(source_version)
       WHERE common_event_outbox.payload_json::text LIKE '%' || v.source_version || '%'
     );

  SELECT COUNT(*)
  INTO v_inbox_refs
  FROM common_event_inbox
  WHERE source_run_id = ANY(v_versions)
     OR EXISTS (
       SELECT 1 FROM unnest(v_versions) AS v(source_version)
       WHERE common_event_inbox.payload_json::text LIKE '%' || v.source_version || '%'
          OR common_event_inbox.raw_json::text LIKE '%' || v.source_version || '%'
     );

  SELECT COUNT(*)
  INTO v_checkpoint_refs
  FROM common_event_consumer_checkpoint
  WHERE EXISTS (
    SELECT 1 FROM unnest(v_versions) AS v(source_version)
    WHERE common_event_consumer_checkpoint.checkpoint_payload::text LIKE '%' || v.source_version || '%'
  );

  SELECT COUNT(*)
  INTO v_n2_refs
  FROM common_condition_run
  WHERE source_trade_date = v_trade_date
     OR source_version = ANY(v_versions)
     OR EXISTS (
       SELECT 1 FROM unnest(v_versions) AS v(source_version)
       WHERE common_condition_run.source_versions::text LIKE '%' || v.source_version || '%'
          OR common_condition_run.raw_json::text LIKE '%' || v.source_version || '%'
     );

  SELECT COUNT(*)
  INTO v_n3_refs
  FROM common_market_data_run
  WHERE source_trade_date = v_trade_date
     OR EXISTS (
       SELECT 1 FROM unnest(v_versions) AS v(source_version)
       WHERE common_market_data_run.raw_json::text LIKE '%' || v.source_version || '%'
     );

  SELECT COUNT(*)
  INTO v_n4_refs
  FROM common_trigger_run
  WHERE EXISTS (
    SELECT 1 FROM unnest(v_versions) AS v(source_version)
    WHERE common_trigger_run.raw_json::text LIKE '%' || v.source_version || '%'
  );

  SELECT COUNT(*)
  INTO v_n5_refs
  FROM common_action_run
  WHERE EXISTS (
    SELECT 1 FROM unnest(v_versions) AS v(source_version)
    WHERE common_action_run.raw_json::text LIKE '%' || v.source_version || '%'
  );

  SELECT COUNT(*)
  INTO v_n6_refs
  FROM user_projection_run
  WHERE EXISTS (
    SELECT 1 FROM unnest(v_versions) AS v(source_version)
    WHERE user_projection_run.quality_summary_json::text LIKE '%' || v.source_version || '%'
       OR user_projection_run.source_display_condition_run_id LIKE '%' || v.source_version || '%'
       OR user_projection_run.source_action_run_id LIKE '%' || v.source_version || '%'
  );

  IF v_outbox_refs <> 0
     OR v_inbox_refs <> 0
     OR v_checkpoint_refs <> 0
     OR v_n2_refs <> 0
     OR v_n3_refs <> 0
     OR v_n4_refs <> 0
     OR v_n5_refs <> 0
     OR v_n6_refs <> 0 THEN
    RAISE EXCEPTION
      'Refusing N1 daily catch-up 20260603 rollback: outbox %, inbox %, checkpoint %, N2 %, N3 %, N4 %, N5 %, N6 %',
      v_outbox_refs,
      v_inbox_refs,
      v_checkpoint_refs,
      v_n2_refs,
      v_n3_refs,
      v_n4_refs,
      v_n5_refs,
      v_n6_refs;
  END IF;
END $$;

DELETE FROM board_membership_fact
WHERE trade_date = '20260603'
  AND source_version = 'board_membership_20260603_v1';

DELETE FROM index_membership_fact
WHERE trade_date = '20260603'
  AND source_version = 'index_membership_20260603_v1';

DELETE FROM stock_financial_metrics_fact
WHERE source_trade_date = '20260603'
  AND source_version = 'stock_financial_20260603_v1';

DELETE FROM stock_daily_basic
WHERE trade_date = '20260603'
  AND source_version = 'stock_daily_basic_20260603_v1';

DELETE FROM board_daily_bar_fact
WHERE trade_date = '20260603'
  AND source_version = 'board_daily_20260603_v1';

DELETE FROM index_daily_bar_fact
WHERE trade_date = '20260603'
  AND source_version = 'index_daily_20260603_v1';

DELETE FROM stock_daily_bar_fact
WHERE trade_date = '20260603'
  AND source_version = 'stock_daily_20260603_v1';

DELETE FROM board_identity
WHERE source_version = 'board_identity_20260603_v1';

DELETE FROM index_identity
WHERE source_version = 'index_identity_20260603_v1';

DELETE FROM stock_identity
WHERE source_version = 'stock_identity_20260603_v1';

DELETE FROM common_active_source_version
WHERE source_version = ANY(ARRAY[
  'stock_identity_20260603_v1',
  'index_identity_20260603_v1',
  'board_identity_20260603_v1',
  'stock_daily_20260603_v1',
  'index_daily_20260603_v1',
  'board_daily_20260603_v1',
  'stock_daily_basic_20260603_v1',
  'stock_financial_20260603_v1',
  'index_membership_20260603_v1',
  'board_membership_20260603_v1'
]);

DELETE FROM common_quality_gate_result
WHERE source_version = ANY(ARRAY[
  'stock_identity_20260603_v1',
  'index_identity_20260603_v1',
  'board_identity_20260603_v1',
  'stock_daily_20260603_v1',
  'index_daily_20260603_v1',
  'board_daily_20260603_v1',
  'stock_daily_basic_20260603_v1',
  'stock_financial_20260603_v1',
  'index_membership_20260603_v1',
  'board_membership_20260603_v1'
]);

DELETE FROM common_ingest_batch
WHERE source_version = ANY(ARRAY[
  'stock_identity_20260603_v1',
  'index_identity_20260603_v1',
  'board_identity_20260603_v1',
  'stock_daily_20260603_v1',
  'index_daily_20260603_v1',
  'board_daily_20260603_v1',
  'stock_daily_basic_20260603_v1',
  'stock_financial_20260603_v1',
  'index_membership_20260603_v1',
  'board_membership_20260603_v1'
]);

COMMIT;
