-- N3-B1 realtime_daily_snapshot rollback plan.
-- Review before execution. Generated by N3-B1-preflight; not executed in preflight.
-- Scope: N3 realtime snapshot run, quality, facts, and scoped pending/failed/dead_letter N3 outbox rows.
-- Do not execute if scoped outbox/inbox/checkpoint references exist.

\set ON_ERROR_STOP on
\set source_run_id 'market_data_subscription_20260615_condition_layer_20260612_source_20260612_for_20260615_v1'
\set snapshot_run_id 'realtime_daily_snapshot_20260615_standard_outbox_until_0953__market_data_subscription_20260615_condition_layer_20260612_source_20260612_for_20260615_v1'
\set for_trade_date '20260615'
\set source_condition_run_id 'condition_layer_20260612_source_20260612_for_20260615_v1'

SELECT set_config('app.snapshot_run_id', :'snapshot_run_id', false);

DO $$
DECLARE
  target_snapshot_run_id TEXT := current_setting('app.snapshot_run_id');
  scoped_outbox_refs_must_be_zero BIGINT := 0;
  delivered_or_delivering_outbox_rows_must_be_zero BIGINT := 0;
  downstream_inbox_rows_must_be_zero BIGINT := 0;
  checkpoint_refs_must_be_zero BIGINT := 0;
  realtime_projection_refs BIGINT := 0;
  trigger_refs BIGINT := 0;
  trigger_state_refs BIGINT := 0;
  action_refs BIGINT := 0;
  n6_refs BIGINT := 0;
  downstream_touched_refs BIGINT := 0;
  worker_started_refs BIGINT := 0;
BEGIN
  SELECT count(*) INTO delivered_or_delivering_outbox_rows_must_be_zero
  FROM common_event_outbox
  WHERE source_layer = 'N3_market_data'
    AND source_run_id = target_snapshot_run_id
    AND status IN ('delivering', 'delivered');

  SELECT count(*) INTO downstream_inbox_rows_must_be_zero
  FROM common_event_inbox
  WHERE source_layer = 'N3_market_data'
    AND source_run_id = target_snapshot_run_id;

  SELECT count(*) INTO checkpoint_refs_must_be_zero
  FROM common_event_consumer_checkpoint
  WHERE checkpoint_payload::TEXT LIKE '%' || target_snapshot_run_id || '%';

  IF to_regclass('stock_realtime_projection_metric') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM stock_realtime_projection_metric WHERE to_jsonb(stock_realtime_projection_metric)::TEXT LIKE $1'
      INTO realtime_projection_refs USING '%' || target_snapshot_run_id || '%';
  END IF;
  IF to_regclass('index_realtime_projection_metric') IS NOT NULL THEN
    EXECUTE 'SELECT $1 + count(*) FROM index_realtime_projection_metric WHERE to_jsonb(index_realtime_projection_metric)::TEXT LIKE $2'
      INTO realtime_projection_refs USING realtime_projection_refs, '%' || target_snapshot_run_id || '%';
  END IF;
  IF to_regclass('board_realtime_projection_metric') IS NOT NULL THEN
    EXECUTE 'SELECT $1 + count(*) FROM board_realtime_projection_metric WHERE to_jsonb(board_realtime_projection_metric)::TEXT LIKE $2'
      INTO realtime_projection_refs USING realtime_projection_refs, '%' || target_snapshot_run_id || '%';
  END IF;

  SELECT count(*) INTO trigger_refs
  FROM common_trigger_match
  WHERE raw_json::TEXT LIKE '%' || target_snapshot_run_id || '%'
     OR source_event_id LIKE '%' || target_snapshot_run_id || '%';

  IF to_regclass('common_trigger_state') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM common_trigger_state WHERE to_jsonb(common_trigger_state)::TEXT LIKE $1'
      INTO trigger_state_refs USING '%' || target_snapshot_run_id || '%';
  END IF;

  SELECT count(*) INTO action_refs
  FROM common_action_event
  WHERE source_market_data_run_id = target_snapshot_run_id
     OR source_market_trace::TEXT LIKE '%' || target_snapshot_run_id || '%'
     OR payload_json::TEXT LIKE '%' || target_snapshot_run_id || '%'
     OR trace_json::TEXT LIKE '%' || target_snapshot_run_id || '%';

  IF to_regclass('user_projection_run') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM user_projection_run WHERE to_jsonb(user_projection_run)::TEXT LIKE $1'
      INTO n6_refs USING '%' || target_snapshot_run_id || '%';
  END IF;
  IF to_regclass('user_signal_projection') IS NOT NULL THEN
    EXECUTE 'SELECT $1 + count(*) FROM user_signal_projection WHERE to_jsonb(user_signal_projection)::TEXT LIKE $2'
      INTO n6_refs USING n6_refs, '%' || target_snapshot_run_id || '%';
  END IF;
  IF to_regclass('user_signal_card') IS NOT NULL THEN
    EXECUTE 'SELECT $1 + count(*) FROM user_signal_card WHERE to_jsonb(user_signal_card)::TEXT LIKE $2'
      INTO n6_refs USING n6_refs, '%' || target_snapshot_run_id || '%';
  END IF;
  IF to_regclass('user_notification_queue') IS NOT NULL THEN
    EXECUTE 'SELECT $1 + count(*) FROM user_notification_queue WHERE to_jsonb(user_notification_queue)::TEXT LIKE $2'
      INTO n6_refs USING n6_refs, '%' || target_snapshot_run_id || '%';
  END IF;

  SELECT count(*) INTO downstream_touched_refs
  FROM common_market_data_run
  WHERE run_id = target_snapshot_run_id AND downstream_layers_touched = true;

  SELECT count(*) INTO worker_started_refs
  FROM common_market_data_run
  WHERE run_id = target_snapshot_run_id AND worker_started = true;

  IF scoped_outbox_refs_must_be_zero <> 0
     OR delivered_or_delivering_outbox_rows_must_be_zero <> 0
     OR downstream_inbox_rows_must_be_zero <> 0
     OR checkpoint_refs_must_be_zero <> 0
     OR realtime_projection_refs <> 0
     OR trigger_refs <> 0
     OR trigger_state_refs <> 0
     OR action_refs <> 0
     OR n6_refs <> 0
     OR downstream_touched_refs <> 0
     OR worker_started_refs <> 0 THEN
    RAISE EXCEPTION
      'N3-B1 rollback blocked for %, outbox=%, delivered_or_delivering=%, inbox=%, checkpoint=%, realtime_projection=%, trigger=%, trigger_state=%, action=%, n6=%, downstream_touched=%, worker=%',
      target_snapshot_run_id, scoped_outbox_refs_must_be_zero, delivered_or_delivering_outbox_rows_must_be_zero,
      downstream_inbox_rows_must_be_zero, checkpoint_refs_must_be_zero, realtime_projection_refs, trigger_refs,
      trigger_state_refs, action_refs, n6_refs, downstream_touched_refs, worker_started_refs;
  END IF;
END $$;

BEGIN;

-- Delete scoped pending/failed/dead_letter N3 outbox rows generated by this B1 run.
DELETE FROM common_event_outbox
WHERE source_layer = 'N3_market_data'
  AND source_run_id = :'snapshot_run_id'
  AND status IN ('pending', 'failed', 'dead_letter');

DELETE FROM stock_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND stock_identity_key LIKE 'stock:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM index_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND index_identity_key LIKE 'index:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM board_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND board_identity_key LIKE 'board:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_quality_item
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND layer_scope = 'market_data_run'
  AND details ->> 'source_run_id' = :'source_run_id'
  AND details ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_run
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND (raw_json ->> 'snapshot_run_id' = :'snapshot_run_id' OR raw_json ->> 'run_id' = :'snapshot_run_id')
  AND downstream_layers_touched = false
  AND worker_started = false;

COMMIT;
