-- N3-A1 previous_day_minute_bar_1m rollback plan.
-- Review before execution. Generated by N3-A1-preflight; not executed in preflight.
-- Scope: N3 previous-day minute preload rows only. It intentionally does not write or delete event infrastructure.

\set ON_ERROR_STOP on
\set source_run_id 'market_data_subscription_20260603_condition_layer_20260602_source_20260602_v1'
\set preload_run_id 'previous_day_minute_preload_20260602_for_20260603__market_data_subscription_20260603_condition_layer_20260602_source_20260602_v1'
\set previous_day_minute_date '20260602'
\set source_condition_run_id 'condition_layer_20260602_source_20260602_v1'

BEGIN;

DO $$
DECLARE
  v_preload_run_id TEXT := 'previous_day_minute_preload_20260602_for_20260603__market_data_subscription_20260603_condition_layer_20260602_source_20260602_v1';
  v_count BIGINT;
BEGIN
  SELECT count(*) INTO v_count
  FROM common_event_outbox
  WHERE source_run_id = v_preload_run_id;

  IF v_count <> 0 THEN
    RAISE EXCEPTION 'Refusing N3-A1 rollback: common_event_outbox has % rows for %', v_count, v_preload_run_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM common_event_inbox
  WHERE source_run_id = v_preload_run_id;

  IF v_count <> 0 THEN
    RAISE EXCEPTION 'Refusing N3-A1 rollback: common_event_inbox has % rows for %', v_count, v_preload_run_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM common_event_consumer_checkpoint
  WHERE checkpoint_payload::TEXT LIKE '%' || v_preload_run_id || '%';

  IF v_count <> 0 THEN
    RAISE EXCEPTION 'Refusing N3-A1 rollback: common_event_consumer_checkpoint references % in % rows', v_preload_run_id, v_count;
  END IF;
END $$;

DELETE FROM stock_previous_day_minute_preload_status
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM stock_minute_bar_1m
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND is_previous_day_preload = true
  AND stock_identity_key LIKE 'stock:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM index_previous_day_minute_preload_status
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM index_minute_bar_1m
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND is_previous_day_preload = true
  AND index_identity_key LIKE 'index:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM board_previous_day_minute_preload_status
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM board_minute_bar_1m
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND is_previous_day_preload = true
  AND board_identity_key LIKE 'board:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM common_market_data_quality_item
WHERE run_id = :'preload_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND details ->> 'source_run_id' = :'source_run_id'
  AND details ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM common_market_data_run
WHERE run_id = :'preload_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id'
  AND downstream_layers_touched = false
  AND worker_started = false;

COMMIT;
