-- N3-A1 previous-day minute cumulative amount schema rollback draft.
-- Artifact only: do not execute outside an explicit schema rollback gate.

DROP INDEX IF EXISTS stock_previous_day_minute_cumulative_source_identity_minute_uidx;
DROP INDEX IF EXISTS stock_previous_day_minute_cumulative_run_identity_idx;
DROP INDEX IF EXISTS stock_previous_day_minute_cumulative_trade_date_idx;
DROP INDEX IF EXISTS stock_previous_day_minute_cumulative_identity_minute_idx;
DROP TABLE IF EXISTS stock_previous_day_minute_cumulative;

DROP INDEX IF EXISTS index_previous_day_minute_cumulative_source_identity_minute_uidx;
DROP INDEX IF EXISTS index_previous_day_minute_cumulative_run_identity_idx;
DROP INDEX IF EXISTS index_previous_day_minute_cumulative_trade_date_idx;
DROP INDEX IF EXISTS index_previous_day_minute_cumulative_identity_minute_idx;
DROP TABLE IF EXISTS index_previous_day_minute_cumulative;

DROP INDEX IF EXISTS board_previous_day_minute_cumulative_source_identity_minute_uidx;
DROP INDEX IF EXISTS board_previous_day_minute_cumulative_run_identity_idx;
DROP INDEX IF EXISTS board_previous_day_minute_cumulative_trade_date_idx;
DROP INDEX IF EXISTS board_previous_day_minute_cumulative_identity_minute_idx;
DROP TABLE IF EXISTS board_previous_day_minute_cumulative;
