-- N3-A1 previous_day_minute_bar_1m rollback plan.
-- Review before execution. Generated by N3-A1-preflight; not executed in preflight.
-- Scope: N3 previous-day minute preload rows only. It intentionally does not touch common_event_outbox.

\set ON_ERROR_STOP on
\set source_run_id 'market_data_subscription_20260525_condition_layer_20260522_to_20260525_20260524014029_execute'
\set preload_run_id 'previous_day_minute_preload_20260522_for_20260525__market_data_subscription_20260525_condition_layer_20260522_to_20260525_20260524014029_execute'
\set previous_day_minute_date '20260522'
\set source_condition_run_id 'condition_layer_20260522_to_20260525_20260524014029_execute'

BEGIN;

DELETE FROM stock_previous_day_minute_preload_status
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM stock_minute_bar_1m
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND is_previous_day_preload = true
  AND stock_identity_key LIKE 'stock:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM index_previous_day_minute_preload_status
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM index_minute_bar_1m
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND is_previous_day_preload = true
  AND index_identity_key LIKE 'index:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM board_previous_day_minute_preload_status
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM board_minute_bar_1m
WHERE run_id = :'preload_run_id'
  AND trade_date = :'previous_day_minute_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND is_previous_day_preload = true
  AND board_identity_key LIKE 'board:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM common_market_data_quality_item
WHERE run_id = :'preload_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND details ->> 'source_run_id' = :'source_run_id'
  AND details ->> 'preload_run_id' = :'preload_run_id';

DELETE FROM common_market_data_run
WHERE run_id = :'preload_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'preload_run_id' = :'preload_run_id'
  AND downstream_layers_touched = false
  AND worker_started = false;

COMMIT;
