-- N3-B1 realtime_daily_snapshot rollback plan.
-- Review before execution. Generated by N3-B1-preflight; not executed in preflight.
-- Scope: N3 realtime snapshot run rows and its N3 common_event_outbox rows only.
-- Do not execute if outbox rows were delivered or consumed downstream.

\set ON_ERROR_STOP on
\set source_run_id 'market_data_subscription_20260525_condition_layer_20260522_to_20260525_20260525102249_execute'
\set snapshot_run_id 'realtime_daily_snapshot_20260525__market_data_subscription_20260525_condition_layer_20260522_to_20260525_20260525102249_execute'
\set for_trade_date '20260525'
\set source_condition_run_id 'condition_layer_20260522_to_20260525_20260525102249_execute'

-- Precheck: this count must be 0 before rollback.
SELECT count(*) AS delivered_or_delivering_outbox_rows_must_be_zero
FROM common_event_outbox
WHERE source_layer = 'N3_market_data'
  AND source_run_id = :'snapshot_run_id'
  AND event_type IN ('MarketDataDelayed', 'MarketDataMissing', 'MarketDisplaySnapshotUpdated', 'MarketSnapshotUpdated')
  AND status IN ('delivering', 'delivered');

-- Precheck: this count must be 0 before rollback.
SELECT count(*) AS downstream_inbox_rows_must_be_zero
FROM common_event_inbox
WHERE source_layer = 'N3_market_data'
  AND source_run_id = :'snapshot_run_id';

BEGIN;

DELETE FROM common_event_outbox
WHERE source_layer = 'N3_market_data'
  AND source_run_id = :'snapshot_run_id'
  AND event_type IN ('MarketDataDelayed', 'MarketDataMissing', 'MarketDisplaySnapshotUpdated', 'MarketSnapshotUpdated')
  AND status IN ('pending', 'failed', 'dead_letter');

DELETE FROM stock_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND stock_identity_key LIKE 'stock:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM index_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND index_identity_key LIKE 'index:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM board_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND board_identity_key LIKE 'board:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_quality_item
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND layer_scope = 'market_data_run'
  AND details ->> 'source_run_id' = :'source_run_id'
  AND details ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_run
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id'
  AND downstream_layers_touched = false
  AND worker_started = false;

COMMIT;
