-- N3-B1 realtime_daily_snapshot rollback plan.
-- Review before execution. Generated by N3-B1-preflight; not executed in preflight.
-- Scope: B1 fact-only snapshot rows, quality rows, and run row for the scoped snapshot_run_id.
-- Hard-fail before the first DELETE if event infra, downstream, worker, or consumer refs exist.
-- This rollback does not DELETE/UPDATE common_event_outbox, common_event_inbox, checkpoint,
-- N2 condition rows, N3 subscription rows, A1 minute facts, N4/N5/N6 facts, or user delivery state.

\set ON_ERROR_STOP on
\set source_run_id 'market_data_subscription_20260603_condition_layer_20260602_source_20260602_v1'
\set snapshot_run_id 'realtime_snapshot_20260603_market_data_subscription_20260603_condition_layer_20260602_source_20260602_v1'
\set for_trade_date '20260603'
\set source_condition_run_id 'condition_layer_20260602_source_20260602_v1'

BEGIN;

DO $$
DECLARE
  v_snapshot_run_id TEXT := 'realtime_snapshot_20260603_market_data_subscription_20260603_condition_layer_20260602_source_20260602_v1';
  v_outbox_refs BIGINT := 0;
  v_inbox_refs BIGINT := 0;
  v_checkpoint_refs BIGINT := 0;
  v_downstream_refs BIGINT := 0;
  v_downstream_layers_touched BOOLEAN := FALSE;
  v_worker_started BOOLEAN := FALSE;
  v_scan RECORD;
  v_scan_count BIGINT := 0;
BEGIN
  SELECT count(*)
  INTO v_outbox_refs
  FROM common_event_outbox
  WHERE source_layer = 'N3_market_data'
    AND (
      source_run_id = v_snapshot_run_id
      OR payload_json::TEXT LIKE '%' || v_snapshot_run_id || '%'
    );

  SELECT count(*)
  INTO v_inbox_refs
  FROM common_event_inbox
  WHERE source_layer = 'N3_market_data'
    AND (
      source_run_id = v_snapshot_run_id
      OR payload_json::TEXT LIKE '%' || v_snapshot_run_id || '%'
    );

  SELECT count(*)
  INTO v_checkpoint_refs
  FROM common_event_consumer_checkpoint
  WHERE checkpoint_payload::TEXT LIKE '%' || v_snapshot_run_id || '%';

  SELECT
    COALESCE(bool_or(downstream_layers_touched), FALSE),
    COALESCE(bool_or(worker_started), FALSE)
  INTO v_downstream_layers_touched, v_worker_started
  FROM common_market_data_run
  WHERE run_id = v_snapshot_run_id;

  -- N4/N5/N6 downstream refs are scanned dynamically so additive downstream tables are guarded too.
  -- Covered namespaces: common_trigger_%, common_action_%, user_projection, user_signal, notification.
  FOR v_scan IN
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND data_type IN ('text', 'character varying', 'json', 'jsonb')
      AND (
        table_name LIKE 'common_trigger_%'
        OR table_name LIKE 'stock_trigger_%'
        OR table_name LIKE 'index_trigger_%'
        OR table_name LIKE 'board_trigger_%'
        OR table_name LIKE 'common_action_%'
        OR table_name LIKE 'stock_action_%'
        OR table_name LIKE 'index_action_%'
        OR table_name LIKE 'board_action_%'
        OR table_name LIKE '%user_projection%'
        OR table_name LIKE '%user_signal%'
        OR table_name LIKE '%notification%'
      )
  LOOP
    EXECUTE format(
      'SELECT count(*) FROM public.%I WHERE %I::TEXT LIKE $1',
      v_scan.table_name,
      v_scan.column_name
    )
    INTO v_scan_count
    USING '%' || v_snapshot_run_id || '%';

    v_downstream_refs := v_downstream_refs + COALESCE(v_scan_count, 0);
  END LOOP;

  IF v_outbox_refs <> 0
     OR v_inbox_refs <> 0
     OR v_checkpoint_refs <> 0
     OR v_downstream_refs <> 0
     OR v_downstream_layers_touched
     OR v_worker_started THEN
    RAISE EXCEPTION
      'N3-B1 rollback blocked for snapshot_run_id %, outbox_refs=%, inbox_refs=%, checkpoint_refs=%, downstream_refs=%, downstream_layers_touched=%, worker_started=%',
      v_snapshot_run_id,
      v_outbox_refs,
      v_inbox_refs,
      v_checkpoint_refs,
      v_downstream_refs,
      v_downstream_layers_touched,
      v_worker_started;
  END IF;
END $$;

DELETE FROM stock_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND stock_identity_key LIKE 'stock:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM index_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND index_identity_key LIKE 'index:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM board_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND board_identity_key LIKE 'board:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_quality_item
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND layer_scope = 'market_data_run'
  AND details ->> 'source_run_id' = :'source_run_id'
  AND details ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_run
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND (raw_json ->> 'snapshot_run_id' = :'snapshot_run_id' OR raw_json ->> 'run_id' = :'snapshot_run_id')
  AND downstream_layers_touched = false
  AND worker_started = false;

COMMIT;
