-- N3-B1 realtime_daily_snapshot rollback plan.
-- Review before execution. Generated by N3-B1-preflight; not executed in preflight.
-- Scope: N3 realtime snapshot run rows and quality rows only when writes_outbox=false.
-- Do not execute if scoped outbox/inbox/checkpoint references exist.

\set ON_ERROR_STOP on
\set source_run_id 'market_data_subscription_20260528_condition_layer_20260527_source_20260527_v2'
\set snapshot_run_id 'realtime_snapshot_20260528_market_data_subscription_20260528_condition_layer_20260527_source_20260527_v2'
\set for_trade_date '20260528'
\set source_condition_run_id 'condition_layer_20260527_source_20260527_v2'

-- Precheck: this count must be 0 before rollback.
SELECT count(*) AS scoped_outbox_refs_must_be_zero
FROM common_event_outbox
WHERE source_layer = 'N3_market_data'
  AND source_run_id = :'snapshot_run_id';

-- Precheck: this count must be 0 before rollback.
SELECT count(*) AS downstream_inbox_rows_must_be_zero
FROM common_event_inbox
WHERE source_layer = 'N3_market_data'
  AND source_run_id = :'snapshot_run_id';

-- Precheck: this count must be 0 before rollback.
SELECT count(*) AS checkpoint_refs_must_be_zero
FROM common_event_consumer_checkpoint
WHERE checkpoint_payload::TEXT LIKE '%' || :'snapshot_run_id' || '%';

BEGIN;

DELETE FROM stock_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND stock_identity_key LIKE 'stock:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM index_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND index_identity_key LIKE 'index:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM board_realtime_daily_snapshot
WHERE run_id = :'snapshot_run_id'
  AND for_trade_date = :'for_trade_date'
  AND trade_date = :'for_trade_date'
  AND source_condition_run_id = :'source_condition_run_id'
  AND board_identity_key LIKE 'board:%'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND raw_json ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_quality_item
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND layer_scope = 'market_data_run'
  AND details ->> 'source_run_id' = :'source_run_id'
  AND details ->> 'snapshot_run_id' = :'snapshot_run_id';

DELETE FROM common_market_data_run
WHERE run_id = :'snapshot_run_id'
  AND source_condition_run_id = :'source_condition_run_id'
  AND for_trade_date = :'for_trade_date'
  AND raw_json ->> 'source_run_id' = :'source_run_id'
  AND (raw_json ->> 'snapshot_run_id' = :'snapshot_run_id' OR raw_json ->> 'run_id' = :'snapshot_run_id')
  AND downstream_layers_touched = false
  AND worker_started = false;

COMMIT;
