-- N3 intraday B2 rollback for run_id=realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1
-- Generated by dynamic child artifact generator.
-- Scope: only this B2 run's scoped facts, quality rows, and run row.
DO $$
DECLARE
  v_run_id text := 'realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1';
  v_source_run_id text := 'market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1';
  v_table text;
  v_count bigint;
  v_has_source_run_id boolean;
  v_has_payload_json boolean;
BEGIN
  SELECT count(*) INTO v_count
  FROM common_market_data_run
  WHERE run_id IN (v_run_id, v_source_run_id)
    AND (COALESCE(downstream_layers_touched, false) OR COALESCE(worker_started, false));
  IF v_count > 0 THEN
    RAISE EXCEPTION 'rollback blocked: downstream_layers_touched or worker_started for %', v_run_id;
  END IF;

  FOREACH v_table IN ARRAY ARRAY['common_event_outbox', 'common_event_inbox', 'common_event_consumer_checkpoint', 'stock_realtime_projection_metric', 'index_realtime_projection_metric', 'board_realtime_projection_metric', 'common_trigger_state', 'common_trigger_match', 'common_action_confirmation', 'common_action_event', 'user_card_projection', 'user_signal_projection', 'user_notification_queue']
  LOOP
    IF to_regclass('public.' || v_table) IS NOT NULL THEN
      SELECT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = v_table AND column_name = 'source_run_id'
      ) INTO v_has_source_run_id;
      IF v_has_source_run_id THEN
        EXECUTE format('SELECT count(*) FROM %I WHERE source_run_id IN ($1, $2)', v_table)
          INTO v_count USING v_run_id, v_source_run_id;
        IF v_count > 0 THEN
          RAISE EXCEPTION 'rollback blocked: downstream source_run_id refs in %. count=%', v_table, v_count;
        END IF;
      END IF;

      SELECT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = v_table AND column_name = 'payload_json'
      ) INTO v_has_payload_json;
      IF v_has_payload_json THEN
        EXECUTE format('SELECT count(*) FROM %I WHERE payload_json::text LIKE $1', v_table)
          INTO v_count USING '%' || v_run_id || '%';
        IF v_count > 0 THEN
          RAISE EXCEPTION 'rollback blocked: downstream payload refs in %. count=%', v_table, v_count;
        END IF;
      END IF;
    END IF;
  END LOOP;
END $$;

DELETE FROM stock_realtime_projection_metric WHERE projection_run_id = 'realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1';
DELETE FROM index_realtime_projection_metric WHERE projection_run_id = 'realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1';
DELETE FROM board_realtime_projection_metric WHERE projection_run_id = 'realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1';
DELETE FROM common_market_data_quality_item WHERE run_id = 'realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1' OR source_run_id = 'realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1';
DELETE FROM common_market_data_run WHERE run_id = 'realtime_projection_metric_20260612_auction_0930__realtime_daily_snapshot_20260612_auction_0930__market_data_subscription_20260612_condition_layer_20260611_source_20260611_for_20260612_v1';
