-- Scoped rollback for 20260630 10:16 N3P trigger-proof target.
-- Scope: proposed N3P target only. Do not delete source payload lineage run.
-- Generated by INTRADAY_N3P_20260630_1016_TRIGGER_PROOF_EXECUTE_GATE.

BEGIN;

DO $$
DECLARE
  v_run_id text := 'realtime_action_confirmation_metric_20260630_until_1016__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1';
  v_count bigint;
  v_table text;
  v_predicate text;
BEGIN
  SELECT count(*) INTO v_count FROM common_event_outbox WHERE (source_run_id = v_run_id OR payload_json::text LIKE '%' || v_run_id || '%') AND status IN ('delivered', 'delivering');
  IF v_count <> 0 THEN RAISE EXCEPTION 'rollback blocked: delivered/delivering outbox refs=% for %', v_count, v_run_id; END IF;
  SELECT count(*) INTO v_count FROM common_event_inbox WHERE source_run_id = v_run_id OR payload_json::text LIKE '%' || v_run_id || '%' OR raw_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN RAISE EXCEPTION 'rollback blocked: inbox refs=% for %', v_count, v_run_id; END IF;
  SELECT count(*) INTO v_count FROM common_event_consumer_checkpoint WHERE checkpoint_payload::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN RAISE EXCEPTION 'rollback blocked: checkpoint refs=% for %', v_count, v_run_id; END IF;
  SELECT count(*) INTO v_count FROM common_trigger_run WHERE source_market_data_run_id = v_run_id OR raw_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN RAISE EXCEPTION 'rollback blocked: N4 refs=% for %', v_count, v_run_id; END IF;
  SELECT count(*) INTO v_count FROM common_action_run WHERE raw_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN RAISE EXCEPTION 'rollback blocked: N5 action run refs=% for %', v_count, v_run_id; END IF;
  SELECT count(*) INTO v_count FROM common_action_event WHERE source_market_data_run_id = v_run_id OR payload_json::text LIKE '%' || v_run_id || '%' OR trace_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN RAISE EXCEPTION 'rollback blocked: N5 action event refs=% for %', v_count, v_run_id; END IF;
  FOR v_table IN
    SELECT table_name
    FROM (
      VALUES
        ('stock_action_fact'),
        ('index_action_fact'),
        ('board_action_fact'),
        ('common_action_quality_item'),
        ('common_action_run'),
        ('common_action_tracking_state'),
        ('common_action_event'),
        ('common_position_event'),
        ('common_position_state'),
        ('user_projection_run'),
        ('user_signal_projection'),
        ('user_signal_card'),
        ('user_signal_decision'),
        ('user_notification_queue'),
        ('user_monitor_stock'),
        ('user_monitor_index'),
        ('user_monitor_board'),
        ('user_sim_order'),
        ('user_sim_position'),
        ('user_sim_trade'),
        ('n6_display_cache_run'),
        ('n6_stock_display_cache'),
        ('n6_index_display_cache'),
        ('n6_board_display_cache'),
        ('n6_virtual_account'),
        ('n6_virtual_cash_ledger'),
        ('n6_virtual_cash_snapshot'),
        ('n6_virtual_order'),
        ('n6_virtual_pnl_snapshot'),
        ('n6_virtual_position'),
        ('n6_virtual_position_event'),
        ('n6_virtual_trade')
    ) AS downstream(table_name)
    WHERE to_regclass('public.' || table_name) IS NOT NULL
  LOOP
    SELECT string_agg(format('%I::text LIKE %L', column_name, '%' || v_run_id || '%'), ' OR ')
      INTO v_predicate
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = v_table
       AND data_type IN ('text', 'character varying', 'jsonb', 'json');
    IF v_predicate IS NOT NULL THEN
      EXECUTE format('SELECT count(*) FROM %I WHERE %s', v_table, v_predicate) INTO v_count;
      IF v_count <> 0 THEN
        RAISE EXCEPTION 'rollback blocked: downstream action/user/sim/N6 refs in %. refs=% for %', v_table, v_count, v_run_id;
      END IF;
    END IF;
  END LOOP;
END $$;

DELETE FROM stock_action_confirmation_projection_metric WHERE projection_run_id = 'realtime_action_confirmation_metric_20260630_until_1016__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1';
DELETE FROM index_action_confirmation_projection_metric WHERE projection_run_id = 'realtime_action_confirmation_metric_20260630_until_1016__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1';
DELETE FROM board_action_confirmation_projection_metric WHERE projection_run_id = 'realtime_action_confirmation_metric_20260630_until_1016__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1';
DELETE FROM common_market_data_quality_item WHERE run_id = 'realtime_action_confirmation_metric_20260630_until_1016__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1';
DELETE FROM common_market_data_run WHERE run_id = 'realtime_action_confirmation_metric_20260630_until_1016__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1';

COMMIT;
