-- Scoped rollback for 20260630 09:35 N3P trigger-proof target.
-- Scope: proposed N3P target only. Do not delete source payload lineage run.
-- Generated by INTRADAY_N3P_20260630_TRIGGER_PROOF_EXECUTE_GATE.

BEGIN;

DO $$
DECLARE
  v_run_id text := "realtime_action_confirmation_metric_20260630_until_0935__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1";
  v_count integer;
BEGIN
  SELECT count(*) INTO v_count
  FROM common_event_outbox
  WHERE (source_run_id = v_run_id OR payload_json::text LIKE '%' || v_run_id || '%')
    AND status IN ('delivered', 'delivering');
  IF v_count <> 0 THEN
    RAISE EXCEPTION 'rollback blocked: delivered/delivering outbox refs=% for %', v_count, v_run_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM common_event_inbox
  WHERE source_run_id = v_run_id OR payload_json::text LIKE '%' || v_run_id || '%' OR raw_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN
    RAISE EXCEPTION 'rollback blocked: inbox refs=% for %', v_count, v_run_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM common_event_consumer_checkpoint
  WHERE checkpoint_payload::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN
    RAISE EXCEPTION 'rollback blocked: checkpoint refs=% for %', v_count, v_run_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM common_trigger_run
  WHERE source_market_data_run_id = v_run_id OR raw_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN
    RAISE EXCEPTION 'rollback blocked: N4 refs=% for %', v_count, v_run_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM common_action_run
  WHERE raw_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN
    RAISE EXCEPTION 'rollback blocked: N5 action run refs=% for %', v_count, v_run_id;
  END IF;

  SELECT count(*) INTO v_count
  FROM common_action_event
  WHERE source_market_data_run_id = v_run_id OR payload_json::text LIKE '%' || v_run_id || '%' OR trace_json::text LIKE '%' || v_run_id || '%';
  IF v_count <> 0 THEN
    RAISE EXCEPTION 'rollback blocked: N5 action event refs=% for %', v_count, v_run_id;
  END IF;
END $$;

DELETE FROM stock_action_confirmation_projection_metric WHERE projection_run_id = "realtime_action_confirmation_metric_20260630_until_0935__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1";
DELETE FROM index_action_confirmation_projection_metric WHERE projection_run_id = "realtime_action_confirmation_metric_20260630_until_0935__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1";
DELETE FROM board_action_confirmation_projection_metric WHERE projection_run_id = "realtime_action_confirmation_metric_20260630_until_0935__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1";
DELETE FROM common_market_data_quality_item WHERE run_id = "realtime_action_confirmation_metric_20260630_until_0935__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1";
DELETE FROM common_market_data_run WHERE run_id = "realtime_action_confirmation_metric_20260630_until_0935__asset_all__b1_source_returned_snapshot_amount_chain_v2_asset_unit_fix_v1_current_period_avg_v1__market_data_subscription_20260630_condition_layer_20260629_source_20260629_for_20260630_v1";

COMMIT;
