-- A-share monitor v3 N3T action-confirmation metric schema draft.
-- Stage: N3T Option A draft only. Requires a later explicit final migration gate.
-- Boundary: N3_market_data N3T tables only; no DB operation is authorized by this file.

CREATE TABLE IF NOT EXISTS stock_n3t_action_confirmation_metric (
  n3t_action_confirmation_metric_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  projection_run_id TEXT NOT NULL,
  projection_schema_version TEXT NOT NULL DEFAULT 'n3t.action_confirmation_metric.v1',
  for_trade_date TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL DEFAULT 'stock' CHECK (asset_kind = 'stock'),
  identity_key TEXT NOT NULL CHECK (identity_key LIKE 'stock:%'),
  metric_time TIMESTAMPTZ NOT NULL,
  metric_minute_label TEXT NOT NULL,
  source_basis TEXT NOT NULL DEFAULT 'N3T_C1_CLOSED' CHECK (source_basis = 'N3T_C1_CLOSED'),
  metric_role TEXT NOT NULL DEFAULT 'action_confirmation' CHECK (metric_role = 'action_confirmation'),
  proof_consumer TEXT NOT NULL DEFAULT 'N5' CHECK (proof_consumer = 'N5'),
  not_n5_final_proof BOOLEAN NOT NULL DEFAULT false CHECK (not_n5_final_proof = false),
  current_price NUMERIC,
  previous_120m_body_high NUMERIC,
  previous_120m_body_low NUMERIC,
  previous_30m_body_high NUMERIC,
  previous_30m_body_low NUMERIC,
  previous_5m_body_high NUMERIC,
  previous_5m_body_low NUMERIC,
  previous_1m_body_high NUMERIC,
  previous_1m_body_low NUMERIC,
  current_1m_amount NUMERIC,
  previous_1m_amount NUMERIC,
  current_5m_amount NUMERIC,
  previous_5m_amount NUMERIC,
  current_5m_virtual_amount NUMERIC,
  previous_5m_full_amount NUMERIC,
  current_30m_closed_elapsed_amount NUMERIC,
  current_30m_virtual_amount NUMERIC,
  previous_day_same_window_amount NUMERIC,
  is_first_1m_of_day BOOLEAN NOT NULL DEFAULT false,
  is_first_5m_of_day BOOLEAN NOT NULL DEFAULT false,
  first_1m_amount_default_pass BOOLEAN NOT NULL DEFAULT false,
  first_5m_amount_default_pass BOOLEAN NOT NULL DEFAULT false,
  source_closed_minute_bar_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
  previous_day_minute_refs JSONB NOT NULL DEFAULT '[]'::JSONB,
  metric_ready BOOLEAN NOT NULL DEFAULT false,
  metric_quality_status TEXT NOT NULL DEFAULT 'blocked',
  blocked_reasons JSONB NOT NULL DEFAULT '[]'::JSONB,
  trace_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(projection_run_id, identity_key, trade_date, metric_minute_label, projection_schema_version),
  CHECK (projection_run_id LIKE 'n3t_action_confirmation_metric_%'),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (trade_date ~ '^[0-9]{8}$'),
  CHECK (current_30m_virtual_amount IS NULL OR current_30m_closed_elapsed_amount IS NULL OR current_30m_virtual_amount = current_30m_closed_elapsed_amount),
  CHECK (current_5m_virtual_amount IS NULL OR current_5m_amount IS NULL OR current_5m_virtual_amount = current_5m_amount),
  CHECK (previous_5m_full_amount IS NULL OR previous_5m_amount IS NULL OR previous_5m_full_amount = previous_5m_amount),
  CHECK (metric_quality_status IN ('passed', 'warning', 'missing', 'failed', 'blocked'))
);

CREATE INDEX IF NOT EXISTS idx_stock_n3t_action_confirmation_metric_run
ON stock_n3t_action_confirmation_metric(projection_run_id, metric_quality_status, metric_ready);

CREATE INDEX IF NOT EXISTS idx_stock_n3t_action_confirmation_metric_identity
ON stock_n3t_action_confirmation_metric(trade_date, identity_key, metric_time DESC);

CREATE TABLE IF NOT EXISTS index_n3t_action_confirmation_metric (
  n3t_action_confirmation_metric_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  projection_run_id TEXT NOT NULL,
  projection_schema_version TEXT NOT NULL DEFAULT 'n3t.action_confirmation_metric.v1',
  for_trade_date TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL DEFAULT 'index' CHECK (asset_kind = 'index'),
  identity_key TEXT NOT NULL CHECK (identity_key LIKE 'index:%'),
  metric_time TIMESTAMPTZ NOT NULL,
  metric_minute_label TEXT NOT NULL,
  source_basis TEXT NOT NULL DEFAULT 'N3T_C1_CLOSED' CHECK (source_basis = 'N3T_C1_CLOSED'),
  metric_role TEXT NOT NULL DEFAULT 'action_confirmation' CHECK (metric_role = 'action_confirmation'),
  proof_consumer TEXT NOT NULL DEFAULT 'N5' CHECK (proof_consumer = 'N5'),
  not_n5_final_proof BOOLEAN NOT NULL DEFAULT false CHECK (not_n5_final_proof = false),
  current_price NUMERIC,
  previous_120m_body_high NUMERIC,
  previous_120m_body_low NUMERIC,
  previous_30m_body_high NUMERIC,
  previous_30m_body_low NUMERIC,
  previous_5m_body_high NUMERIC,
  previous_5m_body_low NUMERIC,
  previous_1m_body_high NUMERIC,
  previous_1m_body_low NUMERIC,
  current_1m_amount NUMERIC,
  previous_1m_amount NUMERIC,
  current_5m_amount NUMERIC,
  previous_5m_amount NUMERIC,
  current_5m_virtual_amount NUMERIC,
  previous_5m_full_amount NUMERIC,
  current_30m_closed_elapsed_amount NUMERIC,
  current_30m_virtual_amount NUMERIC,
  previous_day_same_window_amount NUMERIC,
  is_first_1m_of_day BOOLEAN NOT NULL DEFAULT false,
  is_first_5m_of_day BOOLEAN NOT NULL DEFAULT false,
  first_1m_amount_default_pass BOOLEAN NOT NULL DEFAULT false,
  first_5m_amount_default_pass BOOLEAN NOT NULL DEFAULT false,
  source_closed_minute_bar_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
  previous_day_minute_refs JSONB NOT NULL DEFAULT '[]'::JSONB,
  metric_ready BOOLEAN NOT NULL DEFAULT false,
  metric_quality_status TEXT NOT NULL DEFAULT 'blocked',
  blocked_reasons JSONB NOT NULL DEFAULT '[]'::JSONB,
  trace_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(projection_run_id, identity_key, trade_date, metric_minute_label, projection_schema_version),
  CHECK (projection_run_id LIKE 'n3t_action_confirmation_metric_%'),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (trade_date ~ '^[0-9]{8}$'),
  CHECK (current_30m_virtual_amount IS NULL OR current_30m_closed_elapsed_amount IS NULL OR current_30m_virtual_amount = current_30m_closed_elapsed_amount),
  CHECK (current_5m_virtual_amount IS NULL OR current_5m_amount IS NULL OR current_5m_virtual_amount = current_5m_amount),
  CHECK (previous_5m_full_amount IS NULL OR previous_5m_amount IS NULL OR previous_5m_full_amount = previous_5m_amount),
  CHECK (metric_quality_status IN ('passed', 'warning', 'missing', 'failed', 'blocked'))
);

CREATE INDEX IF NOT EXISTS idx_index_n3t_action_confirmation_metric_run
ON index_n3t_action_confirmation_metric(projection_run_id, metric_quality_status, metric_ready);

CREATE INDEX IF NOT EXISTS idx_index_n3t_action_confirmation_metric_identity
ON index_n3t_action_confirmation_metric(trade_date, identity_key, metric_time DESC);

CREATE TABLE IF NOT EXISTS board_n3t_action_confirmation_metric (
  n3t_action_confirmation_metric_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  projection_run_id TEXT NOT NULL,
  projection_schema_version TEXT NOT NULL DEFAULT 'n3t.action_confirmation_metric.v1',
  for_trade_date TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  asset_kind TEXT NOT NULL DEFAULT 'board' CHECK (asset_kind = 'board'),
  identity_key TEXT NOT NULL CHECK (identity_key LIKE 'board:%'),
  metric_time TIMESTAMPTZ NOT NULL,
  metric_minute_label TEXT NOT NULL,
  source_basis TEXT NOT NULL DEFAULT 'N3T_C1_CLOSED' CHECK (source_basis = 'N3T_C1_CLOSED'),
  metric_role TEXT NOT NULL DEFAULT 'action_confirmation' CHECK (metric_role = 'action_confirmation'),
  proof_consumer TEXT NOT NULL DEFAULT 'N5' CHECK (proof_consumer = 'N5'),
  not_n5_final_proof BOOLEAN NOT NULL DEFAULT false CHECK (not_n5_final_proof = false),
  current_price NUMERIC,
  previous_120m_body_high NUMERIC,
  previous_120m_body_low NUMERIC,
  previous_30m_body_high NUMERIC,
  previous_30m_body_low NUMERIC,
  previous_5m_body_high NUMERIC,
  previous_5m_body_low NUMERIC,
  previous_1m_body_high NUMERIC,
  previous_1m_body_low NUMERIC,
  current_1m_amount NUMERIC,
  previous_1m_amount NUMERIC,
  current_5m_amount NUMERIC,
  previous_5m_amount NUMERIC,
  current_5m_virtual_amount NUMERIC,
  previous_5m_full_amount NUMERIC,
  current_30m_closed_elapsed_amount NUMERIC,
  current_30m_virtual_amount NUMERIC,
  previous_day_same_window_amount NUMERIC,
  is_first_1m_of_day BOOLEAN NOT NULL DEFAULT false,
  is_first_5m_of_day BOOLEAN NOT NULL DEFAULT false,
  first_1m_amount_default_pass BOOLEAN NOT NULL DEFAULT false,
  first_5m_amount_default_pass BOOLEAN NOT NULL DEFAULT false,
  source_closed_minute_bar_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
  previous_day_minute_refs JSONB NOT NULL DEFAULT '[]'::JSONB,
  metric_ready BOOLEAN NOT NULL DEFAULT false,
  metric_quality_status TEXT NOT NULL DEFAULT 'blocked',
  blocked_reasons JSONB NOT NULL DEFAULT '[]'::JSONB,
  trace_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  raw_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(projection_run_id, identity_key, trade_date, metric_minute_label, projection_schema_version),
  CHECK (projection_run_id LIKE 'n3t_action_confirmation_metric_%'),
  CHECK (for_trade_date ~ '^[0-9]{8}$'),
  CHECK (trade_date ~ '^[0-9]{8}$'),
  CHECK (current_30m_virtual_amount IS NULL OR current_30m_closed_elapsed_amount IS NULL OR current_30m_virtual_amount = current_30m_closed_elapsed_amount),
  CHECK (current_5m_virtual_amount IS NULL OR current_5m_amount IS NULL OR current_5m_virtual_amount = current_5m_amount),
  CHECK (previous_5m_full_amount IS NULL OR previous_5m_amount IS NULL OR previous_5m_full_amount = previous_5m_amount),
  CHECK (metric_quality_status IN ('passed', 'warning', 'missing', 'failed', 'blocked'))
);

CREATE INDEX IF NOT EXISTS idx_board_n3t_action_confirmation_metric_run
ON board_n3t_action_confirmation_metric(projection_run_id, metric_quality_status, metric_ready);

CREATE INDEX IF NOT EXISTS idx_board_n3t_action_confirmation_metric_identity
ON board_n3t_action_confirmation_metric(trade_date, identity_key, metric_time DESC);
