-- N5 20260529 live2 canonical action execute rollback.
-- Generated by 20260529 N5 live2 canonical dry-run / contract gate.
-- Execute only after a separately approved N5 canonical execute run needs rollback.
-- Scope:
--   action_run_id: action_consumer_canonical_20260529_live2_trigger_execute_20260529_live2_condition_layer_20260528_source_20260528_v1
--   source_trigger_run_id: trigger_execute_20260529_live2_condition_layer_20260528_source_20260528_v1
--   consumer_name: n5_action_consumer_v1
-- Boundary:
--   Deletes only N5 rows scoped by action_run_id/source_trigger_run_id/consumer_name.
--   Guards downstream N6 refs before deleting.
--   Does not touch N4/N3/N2 facts, N4 outbox status, N6 user projection rows, voice, sim, mobile, real trade, workers, old system, or 025 schema.

BEGIN;

\set action_run_id 'action_consumer_canonical_20260529_live2_trigger_execute_20260529_live2_condition_layer_20260528_source_20260528_v1'
\set source_trigger_run_id 'trigger_execute_20260529_live2_condition_layer_20260528_source_20260528_v1'
\set consumer_name 'n5_action_consumer_v1'

SELECT set_config('n5.rollback_action_run_id', :'action_run_id', false);
SELECT set_config('n5.rollback_source_trigger_run_id', :'source_trigger_run_id', false);
SELECT set_config('n5.rollback_consumer_name', :'consumer_name', false);

DO $$
DECLARE
  v_action_run_id TEXT := current_setting('n5.rollback_action_run_id');
  v_n6_ref_count BIGINT;
BEGIN
  SELECT count(*) INTO v_n6_ref_count
  FROM common_event_inbox
  WHERE source_layer = 'N5_action'
    AND source_run_id = v_action_run_id
    AND (
      consumer_name ILIKE 'n6%%'
      OR consumer_name ILIKE 'user%%'
      OR consumer_name ILIKE '%%projection%%'
      OR consumer_name ILIKE '%%voice%%'
      OR consumer_name ILIKE '%%sim%%'
      OR consumer_name ILIKE '%%mobile%%'
    );
  IF v_n6_ref_count <> 0 THEN
    RAISE EXCEPTION 'N5 canonical action rollback blocked: N6 downstream inbox refs exist for %, count=%', v_action_run_id, v_n6_ref_count;
  END IF;

  IF to_regclass('public.user_projection_run') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM user_projection_run WHERE source_action_run_id = $1' INTO v_n6_ref_count USING v_action_run_id;
    IF v_n6_ref_count <> 0 THEN
      RAISE EXCEPTION 'N5 canonical action rollback blocked: user_projection_run refs exist for %, count=%', v_action_run_id, v_n6_ref_count;
    END IF;
  END IF;

  IF to_regclass('public.user_signal_projection') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM user_signal_projection WHERE source_action_run_id = $1' INTO v_n6_ref_count USING v_action_run_id;
    IF v_n6_ref_count <> 0 THEN
      RAISE EXCEPTION 'N5 canonical action rollback blocked: user_signal_projection refs exist for %, count=%', v_action_run_id, v_n6_ref_count;
    END IF;
  END IF;

  IF to_regclass('public.user_signal_card') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM user_signal_card WHERE source_action_run_id = $1' INTO v_n6_ref_count USING v_action_run_id;
    IF v_n6_ref_count <> 0 THEN
      RAISE EXCEPTION 'N5 canonical action rollback blocked: user_signal_card refs exist for %, count=%', v_action_run_id, v_n6_ref_count;
    END IF;
  END IF;

  IF to_regclass('public.user_notification_queue') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM user_notification_queue WHERE source_action_run_id = $1' INTO v_n6_ref_count USING v_action_run_id;
    IF v_n6_ref_count <> 0 THEN
      RAISE EXCEPTION 'N5 canonical action rollback blocked: user_notification_queue refs exist for %, count=%', v_action_run_id, v_n6_ref_count;
    END IF;
  END IF;
END $$;

SELECT 'common_action_run' AS table_name, count(*) AS row_count
FROM common_action_run
WHERE run_id = :'action_run_id'
UNION ALL
SELECT 'common_action_quality_item', count(*)
FROM common_action_quality_item
WHERE run_id = :'action_run_id'
UNION ALL
SELECT 'stock_action_fact', count(*)
FROM stock_action_fact
WHERE run_id = :'action_run_id'
UNION ALL
SELECT 'index_action_fact', count(*)
FROM index_action_fact
WHERE run_id = :'action_run_id'
UNION ALL
SELECT 'board_action_fact', count(*)
FROM board_action_fact
WHERE run_id = :'action_run_id'
UNION ALL
SELECT 'common_action_event', count(*)
FROM common_action_event
WHERE run_id = :'action_run_id'
UNION ALL
SELECT 'common_event_outbox_n5', count(*)
FROM common_event_outbox
WHERE source_layer = 'N5_action'
  AND source_run_id = :'action_run_id'
UNION ALL
SELECT 'common_event_inbox_n5_consumer', count(*)
FROM common_event_inbox
WHERE consumer_name = :'consumer_name'
  AND source_layer = 'N4_trigger'
  AND source_run_id = :'source_trigger_run_id'
UNION ALL
SELECT 'common_event_consumer_checkpoint_n5_consumer', count(*)
FROM common_event_consumer_checkpoint
WHERE consumer_name = :'consumer_name'
  AND source_layer = 'N4_trigger'
  AND checkpoint_payload ->> 'action_run_id' = :'action_run_id';

WITH scoped_n5_event_ids AS (
  SELECT event_id
  FROM common_event_outbox
  WHERE source_layer = 'N5_action'
    AND source_run_id = :'action_run_id'
  UNION
  SELECT event_id
  FROM common_event_ledger
  WHERE source_layer = 'N5_action'
    AND source_run_id = :'action_run_id'
)
DELETE FROM common_event_delivery_attempt
WHERE event_id IN (SELECT event_id FROM scoped_n5_event_ids);

DELETE FROM common_event_consumer_checkpoint
WHERE consumer_name = :'consumer_name'
  AND source_layer = 'N4_trigger'
  AND checkpoint_payload ->> 'action_run_id' = :'action_run_id';

DELETE FROM common_event_inbox
WHERE consumer_name = :'consumer_name'
  AND source_layer = 'N4_trigger'
  AND source_run_id = :'source_trigger_run_id';

DELETE FROM common_event_outbox
WHERE source_layer = 'N5_action'
  AND source_run_id = :'action_run_id';

DELETE FROM common_event_ledger
WHERE source_layer = 'N5_action'
  AND source_run_id = :'action_run_id';

DELETE FROM common_action_event
WHERE run_id = :'action_run_id';

DELETE FROM board_action_fact
WHERE run_id = :'action_run_id';

DELETE FROM index_action_fact
WHERE run_id = :'action_run_id';

DELETE FROM stock_action_fact
WHERE run_id = :'action_run_id';

DELETE FROM common_action_quality_item
WHERE run_id = :'action_run_id';

DELETE FROM common_action_run
WHERE run_id = :'action_run_id';

COMMIT;
